export const DOLBY_VISION_RPU_PACKED_HEADER_BYTE_LENGTH = 192;
export const DOLBY_VISION_RPU_PACKED_COLOR_BYTE_LENGTH = 112;
export const DOLBY_VISION_RPU_PACKED_NLQ_BYTE_LENGTH = 48;
export const DOLBY_VISION_RPU_PACKED_COMPONENT_BYTE_LENGTH = 960;
export const DOLBY_VISION_RPU_PACKED_COMPONENT_COUNT = 3;
export const DOLBY_VISION_RPU_PACKED_COMPONENT_PIVOT_OFFSET = 16;
export const DOLBY_VISION_RPU_PACKED_COMPONENT_SEGMENT_OFFSET = 64;
export const DOLBY_VISION_RPU_PACKED_COMPONENT_MMR_OFFSET = 192;
export const MAXIMUM_DOLBY_VISION_RPU_PIVOT_COUNT = 9;
export const MAXIMUM_DOLBY_VISION_RPU_SEGMENT_COUNT = 8;
export const MAXIMUM_DOLBY_VISION_RPU_MMR_VECTOR_COUNT = 48;

export const DOLBY_VISION_RPU_BASE_LAYER_BIT_DEPTH_WORD_OFFSET = 12;
export const DOLBY_VISION_RPU_ENHANCEMENT_LAYER_BIT_DEPTH_WORD_OFFSET = 13;
export const DOLBY_VISION_RPU_COLOR_WORD_OFFSET =
    DOLBY_VISION_RPU_PACKED_HEADER_BYTE_LENGTH / Uint32Array.BYTES_PER_ELEMENT;
export const DOLBY_VISION_RPU_NLQ_WORD_OFFSET = (
    DOLBY_VISION_RPU_PACKED_HEADER_BYTE_LENGTH
    + DOLBY_VISION_RPU_PACKED_COLOR_BYTE_LENGTH
) / Uint32Array.BYTES_PER_ELEMENT;
export const DOLBY_VISION_RPU_COMPONENT_WORD_OFFSET = (
    DOLBY_VISION_RPU_PACKED_HEADER_BYTE_LENGTH
    + DOLBY_VISION_RPU_PACKED_COLOR_BYTE_LENGTH
    + DOLBY_VISION_RPU_PACKED_NLQ_BYTE_LENGTH
) / Uint32Array.BYTES_PER_ELEMENT;
export const DOLBY_VISION_RPU_COMPONENT_WORD_STRIDE =
    DOLBY_VISION_RPU_PACKED_COMPONENT_BYTE_LENGTH / Uint32Array.BYTES_PER_ELEMENT;
