export const EXTERNAL_HDR_AUTHORIZATION_FIXTURE_VERSION = 2;
export const EXTERNAL_HDR_AUTHORIZATION_CODED_WIDTH = 1_920;
export const EXTERNAL_HDR_AUTHORIZATION_CODED_HEIGHT = 1_088;
export const EXTERNAL_HDR_AUTHORIZATION_DISPLAY_WIDTH = 1_920;
export const EXTERNAL_HDR_AUTHORIZATION_DISPLAY_HEIGHT = 1_080;
export const EXTERNAL_HDR_AUTHORIZATION_FIXTURE_SHA256 =
    '9d887b9cf249f44a283b92c466791cbad357bea11f3eb9b246b01338304cd098';

export type ExternalHDRAuthorizationFixtureSample = {
    rawYUVCode: readonly [number, number, number]
    sampleX: number
    sampleY: number
};

export const EXTERNAL_HDR_AUTHORIZATION_FIXTURE_SAMPLES:
readonly ExternalHDRAuthorizationFixtureSample[] = [{
    rawYUVCode: [ 64, 512, 512 ],
    sampleX: 0,
    sampleY: 135
}, {
    rawYUVCode: [ 283, 512, 512 ],
    sampleX: 480,
    sampleY: 135
}, {
    rawYUVCode: [ 503, 512, 512 ],
    sampleX: 960,
    sampleY: 135
}, {
    rawYUVCode: [ 722, 512, 512 ],
    sampleX: 1_440,
    sampleY: 135
}, {
    rawYUVCode: [ 940, 512, 512 ],
    sampleX: 1_919,
    sampleY: 135
}, {
    rawYUVCode: [ 525, 612, 412 ],
    sampleX: 240,
    sampleY: 810
}, {
    rawYUVCode: [ 705, 412, 612 ],
    sampleX: 1_200,
    sampleY: 810
}, {
    rawYUVCode: [ 795, 412, 612 ],
    sampleX: 1_680,
    sampleY: 810
}];

// Main10 Level 4.0, limited BT.2020/PQ, one deterministic 1920x1080 display frame
const EXTERNAL_HDR_AUTHORIZATION_ACCESS_UNIT_BASE64 = [
    'AAAAAUABDAH//wIgAAADAJAAAAMAAAMAeJWUCQAAAAFCAQECIAAAAwCQAAADAAADAHigA8CAEQfK2WVlSkwuahIgEggAAAMACAAA',
    'AwDAQAAAAAFEAcBzwYkAAAEoAawVwRC0VBICED8HoPAdg7B0DkHQOQcA4BuDeYZkhbBHCQEcIwRQihGCKEUIoRQjBFCL6h7Ugvwz',
    'BzXpt7bfL/bN/ng9o0nlX3RSFVDSh5ptzQkZoR/Dz6v52ovpTZVktUfgzMtYixp+kueB7rCWdJuRXEhqv+z2HY0oNGaDNUeiwNUW',
    'FlClqNTlwa9yCckJkyq38fzJvX//t0RnZjQZMimEhw1n7L2BE74w/o/2FGepmB7MZit+Kltc2tnoJvq+FsEurOptEmCpgWo2/MTc',
    'izEZo51mBnhdNbklp0wyG1om5F0B41AezxrpTAcuC4nXxjwiVqbyzMge2aI6G2aA8qxTumNmOwlzeUlYmAffBsUMslE/rXTQjIwb',
    'RCEgaP3/QIu9DwA25bz9sEdjIDKKLA+YPyJq3e4pJfPOfZJOie1xHd3sD2z3F4bcWQ8F54JTy9W6/zPoLXp0b+a34xEr9bae/kO2',
    'E1QE/gwMBqSE+w9LfgfgiJ4WZqWFhLGaU7z55Duea0nthGBS9cy+QO8TqGCMTAGVxBo0Rfa+hUM+XoR7PAZXwCi4g0MkdV+EgB4r',
    'lbHJuEr7lEYTehMFSPojHKtSnfv0gqUd009Bat9IunNzhy9FgHZkgsFhJdhRQQK7rheXJHkXDockweZcS5Z642USsU5N3B6YnwY9',
    'S9aD95st3cZycQb5hiEsBe2+XAnue+ClMeLHL7wPRtpS0aCko58W8seStQM3BwIQiRA9CwxxGKNNUXtI2amuC8J01s86rXjDqbEk',
    'a4HwE7BwKW/6WXAYJ1eFMK4M9qecN/KA+Ahl+0OBAedFzJkw+VMTgP6AAJcAAAygAX6oAmAAW1uHK5MnHR4AAAMAAAMAAAon0kFd',
    'W+GKsAF2AIwwBMQJCAaKEAtRGAF8RvV+aQIFy+O/TIHygPppAAADAEQAAAMAAAUAAA7gAAZ/crk0sdLQAAADAAADAAADAAADAARY',
    'AGwAAAMDyAAPcAAG7Jh+SNWvkiugigFunqlcAAADALgAAAMAAChgAHgAAE2TTCrPARcAAAMAAAMAAAMAAAMAAJYAECAAAIKAAe4A',
    'AMSXQ4Vhhqke3AAqTb+nQAAAV4AAAAMAKkAAmYAAgUcrk1qBFwAAAwAAAwAAAwAAAwABTgArwAABeAAGiAACoUQ/7C6wga+gBG2R',
    'mDAAACsAAAMAADcAAOgAAQpuVybKOloAAAMAAAMAAAMAAAMABAQAdQAABCgAEcAAChlwTZ+ZVkaeAC8AjLkAAATIAAADAAogADEA',
    'AEDHphWHgIuAAAADAAADAAADAAADAcIAKIAAAb4AB9gABBOkVwgwyky0APp1WQgAAD5AAAADAL8ABNwABtXXzCrjjtAAAAMAAAMA',
    'AAMAAAMANEAFUAAAPYABAgAAhnOAYStwZ8V4BsFjiwAABIAAAAMAEgAAfIAAz8crk6EBFwAAAwAAAwAAAwAAAwAHcADFAAAIIAAg',
    'IAAQ/pBjcZE5JEAT7G86AAAY4AAAAwCYAARgAAhr98wqI47QAAADAAADAAADAAADAFoACtAAAIAAAgwAAQ/rbHu66y+APWlSSAAA',
    'egAAAwAEfAAhQABEtcrk7vMEAAADAAADAAADAAADAAKcAFgAAAMD3AATAAAKCfB0xvmc3QCpOA/gAAJSAAADABeAAOMAAgo+Vyef',
    'mCAAAAMAAAMAAAMAAAMAHSADRAAAIWAAmoAAUM+AfFEiRegBp6UIwAAH2AAAAwBZAAL4AAbJS+YWHHS0AAADAAADAAADAAADAFcA',
    'B8gAAGYAAZ4AAO3xgyKwfuwDk/aLAAAfoAAAAwJYABTQAD4k0wrgnjtAAAADAAADAAADAAADA4wAaIAABIgAEfAACOoQiS2zITwH',
    'nRaGAAA9QAAABKQAJ+AAavHK5PxzBAAAAwAAAwAAAwAAAwAGOACsAAAJeAAkoAASBGCOejB/qAxOACAAAJOAAAAM8AB/AAGpHyuT',
    '+cwQAAADAAADAAADAAADABqgA1QAACDgAJKAAEoRgPxAZxd+LrqbCitIB02Ce4HqnXvfGbe2NVpIAUmYycNa8X99eGpH7PyVrm3y',
    'GZ3JEHTdcWB0DLRr5bBHdSQ5fqytwvFbI5z/5nC1CmCJ7M07pXm5+LAWGsWJiFf6ty5HWQw9S4k6Pr6D4ZGDuQCfLjYmTU6qS8xd',
    'dJdY54FUFFvQhxbJHh6RJV5bbXdf1KPQkcG01NtuHiZF8hwWSpNa7qMLktQDctQRqi0DblreLwxDt6lyXj07jzC0OJWquk0I93Fx',
    '9Fek7L6hFScKrFU8j0aS9ng/opc9VTA9X2EpY+H1CREty9wEjmQALma0+wEbWcwWRXPQbvpLPkZhDxPjvGoFVuSmYlMvE1CsoxL1',
    'biUH8+V8e/n5tZcNssNYihtVbqNGi2ExyuYOJDrJr7g1ESPpi/6bXyLO93kLR5qonF0QD8F/Z+D3R5WN83uSBGyiaByVXgWm83YR',
    '97HTetNZqUiIqhM9GTK+JOtO0RI+DSRLfj7bgNQPAItTHye3QlXhZ7immPD/6cBuw+DzEclktsnjzvbTD1gxBYMJ8QnmD7D0Cb/b',
    'sM8mPxQcWbyjAff3BsnczIUuXmj+X/Rf6xElUtD04OCwdspLZGfq1jc4Azg+B3Y3qD0qeCX4niO4ibwfVTXUJbMJyrRB+fWgBEsP',
    '//XRhlonkGmkoOLrAQ07XNa8uX4B8mBEheGDhm+QvA/uiV/ueXgey5QuiaHxX++ZyxQ5yQSR5JN6LgydNhS9WRG07F6TgSzmSzz+',
    'I8uM8fH7BzTTpychDv2hza8my2S+b/dhtfUCP2Rgxk9GiT1PMGEf0mqbEBui0+GjGjMbrANvDaqv9Q+A3p2rS2D8euE1pYTo2H4h',
    '/4Gw6H0WTAlS96c1dHdgBSCvvDDPNSoASEEtyNg0Lxs0jWoWyrvGD0vWTbeQ84TgDEPeqMIv4xlWyDBM8nE6C7db2VbWPH04je13',
    '3xf6I1h9vVBG7W/Hw/JbfcxXW2SSKNavcojMUXINQVcCdtqcNAB/41i9Y4RUfDUMiBCF50fLpROnFFobF8XZe5vg6rt08FGmjQrp',
    'tyAWcNmWTrFpvBX5ro2qyHlM3sUCZnf0ID1Sd9NrudoCUMwYL7N7ADC0a1lLZBwWBz9ScRs77oMjfCtaxE5xBPE6aRgPyNlTLiR6',
    'Kfyh5qXFriLN6rJZFNKP3PHSP19fmgI7YBP6vq0akJs0jeVvSPeHzNLYGdss0hReHTjvR3ihl4tsWbhLSLex/Htc4bFbRWr6Y6kC',
    'QGxOVQKR43MXgFSYBA/ReKMY6tPhx9KmBhqiHyjjlOe0x48zufY1bXCeRspBpblzafo6gTjfnbRhZoQgl0xVtVkhpBOmTxsXQqCz',
    '3jFlj8tDvLIkdzNSarDQQyjQBGoHVCiY6aU+EkLmn9mOIr/YIvyfjJWR3C2RT9YefIfavXGYu8V/gqg0nY97GINleHkThxUuEsl5',
    'jyIBhWw/SJYHDi6DnwwfvNNi2inQYgsje9D/3tRrS0+bF1fBpSmB4+lAt8tFaihmQ8aeQqcFLRXV7eMbKAPx9Hh/ELs7cCcoYqXI',
    'BN+1EUDi+CmAfz2NS+asvhzV8hXo6WIJta1pu2vzc/mcPW3FOPwLCUNtv0DrdNGYEzZA83j6AuwGVaRvyaEhSpZZUogFRsy3IwDF',
    '1JkFx74wt4QGAYOepQpEnwcGgJv/fGApSKs2elLxCtXiiKd2E/+4olAMRqOuiIw2CkEEKBNjDuFBVKPtCyAXnQGVOLuK4VcFk6X/',
    'c4YPm+bTELe/sRiYQGoCD+zrws1wTGWYaY/bKFdZ9bAbqrchQgb3D/E86IDPeKN+QJPHeELb5guZUw4z91nAxNG7Fdrlmh6VM1go',
    'sYjrKA6Lx0Ej2LvaTFrDKtOz7+gQNC8fzXA3oi+1gm66YDPLfZXxzWQFi3Ngx4x04RO8evxGfwtcIRf2McLGKfen5GIwqOmx4yHv',
    'hmYCWQkKrVJcx+kzlF6ONeV0XGPShYLDSwPUsafs4KaU0C3CLh6fgEzdqTHystJdXgPPcoZomZ6uZKsjzPVNNi02RZthu1JsjNjT',
    'whfWrozKSRW4BR4U5QlQazGMvHHqvF9QZrsV85qo4Pawq0DY6JdqbxO6P50u+UpqDF/mt9hbxL3AS7QA68DtUf9rWbS2K0QbdMh+',
    'jcgXoJaaN0V3NTgEAXteEnxLC3oiHpwI7ilbNjD67mK5jpBewSkGG3QoOLVAbLdzg8ntjPTx6t22PLRHC8ABNj3YhTkMPE7F6bJX',
    'H+2MAf5gACUSrwZ4bqAD+SiAsoXCTeB26YR+ewAD4+gkRdI7eeCPKKsACCjUG44GAADADQZ+AAADAAADAAADABcUCWHTpkBB0uvM',
    'B+FlIgDyACipGk+8gTXPgOFkqw08EgO1bHgAAAegAWLbhfkfkZQgA9wAJiAAAAMAAbwAAAMAAA7AARcAAFYKE52iRWOsnCgDSkAD',
    'MAAAAwAAAwAAxAAEPAACwACwAATkeaHRZSoAAAMAcwAbC5hAAAADAfgAAAMAACWAAAADAAIsACXAAAwYc9P1sKx104UAbIABUgAA',
    'AwAAAwAARwABpAABNABYAAKePNDospUAAAMAPcANhYCaIAAAAwP4AAADAABrAAADAAAHqAChAAAw0MKUZsKx2L4UAZ4ABnAAAAMA',
    'AAMAAdIACaAACOACBgAPZO9qjMyoAAADAQkARGSd4AAABSAAAAMAAO0AAAMAABHQAWIAAHMiCKlNhWOxfCgDPAAM4AAAAwAAAwAD',
    'pAATYAAQ0ARsACLG6+2kn1AAAAMD3ADYWKFAAAAI8AAAAwAB8AAAAwAAKUADkAABI1OAaHA+hOEk6Ak4AB/gAAADAAADAAdIACeA',
    'ACJACNgARk3X20k+oAAABygB+bCkQAAADJAAAAMAA8gAAAMAAHgACdAAA7VSEaHA+hOEk6Ak4ACAAAADAAADAAAdIAChAACKgCNg',
    'AR83X20k+oAAAByAB+bApuAAAA9QAAADAATkAAADAAChAA3wAAWMUjIaJFY7F8KAM8AA2AAAAwAAAwAAOkABRgABGwBGwAI+br7a',
    'SfUAAAMAOYAPzYCpIAAAFlAAAAMACTgAAAMAAUcAHQAAC3ikZDRIrHYvhQBngAGKAAADAAADAABfAAIoAAGOAG6AAyU72qMzKgAA',
    'AwBEABEZq2AAAB1gAAADAA5wAAADAAIKACjAAA/VWIZ/A+hOEk6Ak4AB4AAAAwAAAwAAgIADBAACwACwAAUFzjVGZlQAAAMAiIAi',
    'Mq1AAAAlIAAAAwAWwAAAAwADfABCgAAbyMMKU2FY7F8KAM8AAyQAAAMAAAMAAL4ABGwAAzAA3QAGWne1RmZUAAADAIiAIjKvIAAA',
    'KyAAAAMAIGAAAAMABdAAeAAAL8KRkNEisdi+FAGeAAYwAAADAAADAAF8AAjYAAZgAboADLTvaozMqAAAAwERAERksQAAAwAzgAAA',
    'AwAs4AAAAwAH0ACxgABB1WIZ/A+hOEk6Ak4AB8AAAAMAAAMAAgIADCAAC0ACwAAUFzjVGZlQAAADAiIAiMiyIAAAN8AAAAMAMAAA',
    'AwAACLgA0AAATwtcoEJFY7F8KAM8AAxgAAADAAADAAL4ABGwAAzAA3QAGWne1RmZUAAAAwIiAIjIs0AAAD5AAAADAC0gAAADAAjg',
    'ALGAAEHVYhn8D6E4SToCTgAHwAAAAwAAAwACAgAMIAALQALAABQXONUZmVAAAAMCIgCIyLRgAABSAAADAABMQAAAAwAPoAFjAACD',
    'qsQz+B9CcJJ0BJwAD4AAAAMAAAMABAQAGEAAFoAFgAAoLnGqMzKgAAAERAERsA=='
].join('');

function decodeBase64(base64: string): Uint8Array {
    const decoded = globalThis.atob(base64);
    const bytes = new Uint8Array(decoded.length);
    for (let byteIndex = 0; byteIndex < decoded.length; byteIndex += 1) {
        bytes[byteIndex] = decoded.charCodeAt(byteIndex);
    }
    return bytes;
}

/** Returns a fresh Annex B access unit for native HDR transport authorization. */
export function createExternalHDRAuthorizationAccessUnit(): Uint8Array {
    return decodeBase64(EXTERNAL_HDR_AUTHORIZATION_ACCESS_UNIT_BASE64);
}
