export const NATIVE_ULTRA_HD_VIDEO_CAPABILITY_FIXTURE_VERSION = 1;
export const NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_HEIGHT = 2_160;
export const NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_WIDTH = 3_840;

export const NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODECS = [
    'hevc',
    'vp9',
    'av1'
] as const;

export type NativeUltraHDVideoCapabilityFixtureCodec =
    typeof NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODECS[number];

export type NativeUltraHDVideoCapabilityFixture = Readonly<{
    codec: NativeUltraHDVideoCapabilityFixtureCodec
    codecString: string
    codedHeight: typeof NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_HEIGHT
    codedWidth: typeof NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_WIDTH
    encodedKeyFrame: Uint8Array
}>;

// Generated with FFmpeg git-862338fe31 from one 3840x2160 black keyframe.
// HEVC is progressive 8-bit Main Level 5.1 Annex B with encoder SEI removed.
// VP9 Profile 0 and AV1 Main retain only the first IVF frame payload.
const HEVC_MAIN_KEY_FRAME_BASE64 = [
    'AAAAAUABDAH//yFgAAADAJAAAAMAAAMAmZWUCQAAAAFCAQEhYAAAAwCQAAADAAADAJmgAeAgAhxZZWVKTC8BaAgAAAMACAAAAwDA',
    'QAAAAAFEAcBzwYkAAAEoAax0CIaaGGB+B955111xxtttttttpppppppppppppppppppppppppppppppppppppppppppppqAHH//E',
    'MlpWDUyDgAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAcUASFg1Mg4AAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAABYwFjUyDgAA',
    'AwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAREBnkHAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAGpBqcAAADAAADAAADAAAD',
    'AAADAAADAAADAAADAAADAAFLAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADACUgAAADAAADAAADAAADAAADAAADAAADAAAD',
    'AAADAAADAtIAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAABoQAAADAAADAAADAAADAAADAAADAAADAAADAAADAADigAAAAwAA',
    'AwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAFjAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAdcAAAAwAAAwAAAwAAAwAAAwAAAwAA',
    'AwAAAwAAAwBuwAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwE9AAADAAADAAADAAADAAADAAADAAADAAADAAADA3YAAAMAAAMA',
    'AAMAAAMAAAMAAAMAAAMAAAMAAAjoAAADAAADAAADAAADAAADAAADAAADAAADAAARcAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAA',
    'ISAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAADmgAAADAAADAAADAAADAAADAAADAAADAAADAABcQAAAAwAAAwAAAwAAAwAAAwAA',
    'AwAAAwAAAwAAjoAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAANCAAAADAAADAAADAAADAAADAAADAAADAAADAAEjAAADAAADAAAD',
    'AAADAAADAAADAAADAAADAAGBAAADAAADAAADAAADAAADAAADAAADAAADAAHfAAADAAADAAADAAADAAADAAADAAADAAADAAI6AAAD',
    'AAADAAADAAADAAADAAADAAADAAADAAKmAAADAAADAAADAAADAAADAAADAAADAAADAALuAAADAAADAAADAAADAAADAAADAAADAAAD',
    'AANSAAADAAADAAADAAADAAADAAADAAADAAADAAOaAAADAAADAAADAAADAAADAAADAAADAAADAAPmAAADAAADAAADAAADAAADAAAD',
    'AAADAAADAAQMAAADAAADAAADAAADAAADAAADAAADAAADAAREAAADAAADAAADAAADAAADAAADAAADAAADAARcAAADAAADAAADAAAD',
    'AAADAAADAAADAAADAAR0AAADAAADAAADAAADAAADAAADAAADAAADAAR0AAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAAD',
    'AAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASM',
    'AAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAAD',
    'AAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAAD',
    'AAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAAD',
    'AAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAAD',
    'AAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAAD',
    'AASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAAD',
    'AAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAAD',
    'AAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAAD',
    'AAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASM',
    'AAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAASMAAADAAADAAADAAADAAADAAADAAAD',
    'AAADAASMAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAFxA=='
].join('');
const VP9_PROFILE_0_KEY_FRAME_BASE64 = [
    'gkmDQgDv8Ib2ADgkHBlwAABIYfYwAp6P9KgAaxx+JwKTwkSJEiRIkSJEiRIkSJEiRIwySqVKlUqVKpUqVSpUqlSpVPolKpUqVSpU',
    'qlSpVKlSqVKlWOJUqlSpVKlSqVKlUqVKpUqVxUlSqVKlUqVKpUqVSpUqlSpe5KVSpUqlSpVKlSqVKlUqVKscSpVKlSqVKlUqVKpU',
    'qVSpUripKlUqVKpUqVSpUqlSpVKlS9yUqlSpVKlSqVKlUqVKpUqVY4lSqVKlUqVKpUqVSpUqlSpXFSVKpUqVSpUqlSpVKlSqVKl7',
    'kpVKlSqVKlUqVKpUqVSpUqxxKlUqVKpUqVSpUqlSpVKlSuKkqVSpUqlSpVKlSqVKlUqVL3JSqVKlUqVKpUqVSpUqlSpVjiVKpUqV',
    'SpUqlSpVKlSqVKlcVJUqlSpVKlSqVKlUqVKpUqXuSlUqVKpUqVSpUqlSpVKlSrHEqVSpUqlSpVKlSqVKlUqVK4qSpVKlSqVKlUqV',
    'KpUqVSpUvclKpUqVSpUqlSpVKlSqVKlWOJUqlSpVKlSqVKlUqVKpUqVxUlSqVKlUqVKpUqVSpUqlSpe5KVSpUqlSpVKlSqVKlUqV',
    'KscSpVKlSqVKlUqVKpUqVSpUripKlUqVKpUqVSpUqlSpVKlS9yUqlSpVKlSqVKlUqVKpUqVY4lSqVKlUqVKpUqVSpUqlSpXFSVKp',
    'UqVSpUqlSpVKlSqVKl7kpVKlSqVKlUqVKpUqVSpUqxxKlUqVKpUqVSpUqlSpVKlSuKkqVSpUqlSpVKlSqVKlUqVL3JSqVKlUqVKp',
    'UqVSpUqlSpWdDUYL4AeN5QnDhb/Fn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/B',
    'n8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/Bn8GfwZ/BcgA='
].join('');
const AV1_MAIN_KEY_FRAME_BASE64 =
    'EgAKCBsu+/4b+gCAMiMT/AAAFgAAA60ZzuMJVv9/1iP4UzljTt+FOfqhrdS/wJlKIA==';

function decodeBase64(base64: string): Uint8Array {
    const decoded: string = globalThis.atob(base64);
    const bytes: Uint8Array = new Uint8Array(decoded.length);
    for (let byteIndex = 0; byteIndex < decoded.length; byteIndex += 1) {
        bytes[byteIndex] = decoded.charCodeAt(byteIndex);
    }
    return bytes;
}

/** Returns a fresh exact 3840x2160 native SDR output fixture. */
export function createNativeUltraHDVideoCapabilityFixture(
    codec: NativeUltraHDVideoCapabilityFixtureCodec
): NativeUltraHDVideoCapabilityFixture {
    switch (codec) {
        case 'hevc':
            return {
                codec,
                codecString: 'hvc1.1.6.L153.B0',
                codedHeight: NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_HEIGHT,
                codedWidth: NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_WIDTH,
                encodedKeyFrame: decodeBase64(HEVC_MAIN_KEY_FRAME_BASE64)
            };
        case 'vp9':
            return {
                codec,
                codecString: 'vp09.00.51.08',
                codedHeight: NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_HEIGHT,
                codedWidth: NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_WIDTH,
                encodedKeyFrame: decodeBase64(VP9_PROFILE_0_KEY_FRAME_BASE64)
            };
        case 'av1':
            return {
                codec,
                codecString: 'av01.0.12M.08',
                codedHeight: NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_HEIGHT,
                codedWidth: NATIVE_ULTRA_HD_VIDEO_CAPABILITY_CODED_WIDTH,
                encodedKeyFrame: decodeBase64(AV1_MAIN_KEY_FRAME_BASE64)
            };
    }
}
