// Generated by scripts/webgpu/generate_truehd_capability_fixtures.py
// Sources are deterministic synthetic tones; see scripts/webgpu/truehd/fixtures/README.md

import type { Microseconds } from '../MediaTime';
import type { TrueHDDecoderCodec } from './TrueHDSoftwareAudioDecoder';

export type TrueHDExactCapabilityExpectedOutput = Readonly<{
    frameCount: number
    mediaTimeMicroseconds: Microseconds
    pcmFingerprint: number
}>;

export type TrueHDExactCapabilityFixture = Readonly<{
    accessUnits: readonly Uint8Array[]
    bitsPerSample: 24
    channelCount: 2 | 6
    channelMask: number
    codec: TrueHDDecoderCodec
    expectedOutputs: readonly TrueHDExactCapabilityExpectedOutput[]
    majorSyncRecoveryStartIndex: 1
    sampleRate: 48_000 | 96_000 | 192_000
    source: string
    sourceSHA256: string
}>;

type EncodedTrueHDExactCapabilityFixture = Omit<
    TrueHDExactCapabilityFixture,
    'accessUnits' | 'expectedOutputs'
> & Readonly<{
    accessUnitsBase64: readonly string[]
    expectedOutputs: readonly Readonly<{
        frameCount: number
        mediaTimeMicroseconds: number
        pcmFingerprint: number
    }>[]
}>;

const ENCODED_TRUEHD_EXACT_CAPABILITY_FIXTURES = Object.freeze([
    Object.freeze({
        accessUnitsBase64: Object.freeze([
            'gGL/2Phyb7oAUKABt1IAAAAAjH8QFAAAAAAAAAAANCggUfHqAAABEAAAABKtQAAAAAKUgiIjmgl//rpf/5JQAFwAFevmBgNteWS9x8LekWM62W1m6svBjWqTAO684EWg/oRZIgG+PDCaiOa8iuaJgk5bAQEIAAC748L2yM0Lre4cmNvkOhEMgAAR899vXTq27st7Dnw1rtyrQu0YsqrHivpsF6xiv2qeKzSpIKhCcYn0JpSVOkzJM6MKijIQaJGfhoOsjw==',
            'wCwAAGApkUCA0CCB8TPRx8QOyB5MOR57LNpp4LOBZ1KOBR0HOZhzFOxJ0FO5J2FPop0FQox0CRw51BSYyBBSQqPCSASdDSISnCToipBVISxDWQS3CX6VpA==',
            'YC4AKGArgQHgRRr5EyUjGRNdGzkriQNZM7kTjSvdK8Ej8SwFNBE0RTQ1RG00WUStTHVE1VyxRPFs3UUFfSlVIXVJbUF1fYVhhaGFfZ3FjaGl0Z3VtdWeCc3ka7k=',
            '8CsAUGAogQigQLhYYWWHhiJ4+mInlrYquUxkr5XGW5lr5JmYtlHZfWU/m2Yv+eUwn82rhX5V+HXxauDSYde/r3xLfk1zTXZPcUS3ItpRLKjWRGroZUY=',
            'MCwAeGApgQHgOsalfas5VfSs4lvCsYdu0uXdmvv1linvUF6ftzN+Uux12Jvw12BvPeB4uOmBvvNF9mvr19gvK19WvqF9Oupd5FvI108vH901unV0vABiDw==',
            'wCkAoGAmgQGgO9NOi/4p5MvR/cv8IOCbsc0KfBXMq5FtCPca0IdRnIgzHMhvAfxILx+8euIbSOwisK6h+syoIKTOconNpCyg2gNqDl49lPwYdg==',
            '4CcAyGAkgQGhEfAVCAl0CIQJaAuEErgc6D2QSyLYBrApUQwLSJWJRPVPOiVjMqSoMtRsL0OtK9PvHYN5I9KZI9HUlejKR2hVIro6sCLV',
            'sCgA8GAlgQHhFRqUqlKqSLUjiNPR/I0Wk/RJ6NxCmJGkCUlfPqUy886nWH3UrqJUj+SKkXiR5H0kcScpfkvaXZP8mvUepcFPKitRsqtAl2M=',
            '8CIBGGAfgQihDBqg2gpgXYcQJsKKLYKHEoKMMOIYoowxIHBiRiDknMJE8Q1ixHuSpLEwS8dFzfZ+X7PuWW7p+f/AaLg=',
            'kCwBQGApgQHgOlREqHmRc2NmSM6QnylCSoTVCUp0FGdp0lSgqU1amqV1aosWdWut2ta3t2tfAuW9nDuXlrKvX9rKv5drGwaFzIu6l7Mvad7Uvat7VAB2gw==',
            'sCoBaGAncGvd1sOtd2MGve2sGtd2MGzd1721g0re3hzrW7hy7Wvd0Luba0L+LWz7+BXy7d7bvq2Dbsat9bqqdzYp6lfVoKtNRmak7RlaMpQjwBvn',
            'wCoBkGAngQigRSwdSFJn69/rPlR4teijoY6WuBjg82PtXrP4zOMnTB0wcLrKzssLrCqnoqap6KimljpyKROkTJAqLOhxUWY9iosc8CoIOcxT+L5i',
            '4C4BuGArgQHgRXHNcfFxzWnRYd1htVHtYa1J7UmxUeExvUnlMdlJ3SHtQd0aASnpKg0Z8So5GgUiQSI1GjkSfRopCr0qPQLFGokiuQrBGtES8Rr1CyUjCQtcbzU=',
            'EC0B4GAqUjKQuFM1UDqUOJA81DvRP1O/UkJTwRLFU8QTyBPG1MnUSxVLVc3UzxXQFtCV0xbSF1WXVZfXWFgY2ZhZmdvZ2xrdmd5a3lvfmuBc4NxhnOLAANcQ',
            'YCwCCGApgQGgQbxDmPaxz+Rbx0OWcyEmXcyk+YfyU2bjyFGckxtOdmxdObrwtGZtw9WQuwl2Htw+F+vwON3xv2V0zuels0tmtp3rulk6q+tZ5qO9TAB3wg==',
            'sCsCMGAogQHhGtJWwl7aRsrFxbtu7itaaX29r5f/XOd7je1XtN7DfwXrF6rgn3Z+CPfh3juA7cLYSV0bvD2AUti2AO3Q9fDloKYQrYCmAH7APXgdpc0=',
            'YGQCWPhyb7oAUKABt1IAAAAAjH8QFAAAAAAAAAAANCggU/HqAoABEAAAABOtRgAAAAM0giIj+gmAAk5f/5MP7/7ThCam/Mx2WwU300zRxWv8sduP0Gz0KC2RV+k0SwLsFDPNxPtIgG+PC7xjvy2YunRgP5VgQDIAADb48MWuFnL+S6MFzvoOA3QgAAOdY4XKFwico3ON6mfpXieGogKYyiErk7I2ucukbqG+awpMKHKqzqcq/Wx1s9bfe02wObvbB8xtsEAAAW0=',
            'YCwCgGApkUCA8B97KrZN/JtaF/Mt5l/Wu5l/Zv6uDXu62LXwbGDXxa1/Zx62HWxa+HSxbGLNx6uDRx5WLTw4eTQv4WPJwXuPFv3OK9v3GCvwWl6rwVbGBA==',
            'YCkCqGAmgQGgP9qfqD6i9m/JP2Z7i/I/qG5he3/Z66eNnDdw1Z9WfNk0WsV3NQvVcUW9TtPrkew3sQKTKsyoL6CqgulIZiWMhiH5Bx8biEyWDw==',
            'sCgC0GAlXxx0NgF2Q14QZEGglgPZEVQhcQTBVBNQIQD0w04OTFSwlEeMCzBw4ZHEzikYWMKxx4cuIKRC8k4BLiEAI5ERBEgJGDUQU8AABBU=',
            'kCwC+GApgQHgPRrqBURNJ9cROR9mQvB90QQKB+Pxp+AQTh2JRUZyaQ056lQ2J6wQ3J+0RZB62Sah6+R7CDLR7SPaRayXoR7iTqTcqXvT96btUein1ADxJQ==',
            'cCkDIGAmgQigOBPMF+Ab4B/sJ8g/6H+wn+L+hvsX8F/hvob8J8k+T/RfWHlH3P119Yc1eqvRXfzzU2+bGNrWX7Y3k+xf5DL/9wpfNr31oAAHhA==',
            'MCwDSGApgQHgPm2EuhoUsycozdCRoy1KCqR9N6qw9RysPVZssN1hmsslpgtK9tdtKV1TuJN1LvJNw6xJFswxolwtxnt0rxmmApxF2ArxEGEvxDOItABzYw==',
            'ACoDcGAncQ7hI8RBiI8I3iJcI3jJcJDgHcZNgIcRDfK745iMrg/iMrhRhNbZRfPbZTfRbBffSa5xdTK57bT6ybZT6ipYV6izUXabFUZaDFUcQEUN',
            'YCgDmGAlgQigOUaU7qo7Luz3paE+/LRPYhSO5IsleS3Z3UvumxO6pr096m1dSsnY0s420beFoa8PbkvyXQ94S+DXpcEJgDX4TBEwAbBAO+M=',
            'MCwDwGApgQHgOXXii/XYKi6VYCezUX6e4T3SWuS3SWuSWiSqR1yOrRUyKqRTqGnQziKdPSiKcPSaCPQyx2BQSCGDOwaGCPwJ50RQRxqRPR9sPuCFrABGtQ==',
            'MCkD6GAmgQHgMQKECdCjQIkSFCYRo0JBGgSDUh9GNSk0xFMPTj041OKVEE4lWJVjlQdcMVCmIxaKXDGY9aIbllohwaZCmxlsSbnXRVuhdmzs1g==',
            'MCkEEGAmgQGgObYml99ldZnmyFnedY26F4ldY3yd+lgKISiFpj64iuYri75+uVxnraXObvsdKDK3zpNr7Sr2v97ri83wOsDnH6wPdHjA+1zT4Q==',
            'MCwEOGApgQHgPt497Uu6N3Nv7t7Nv7eDRwb9/Ow7+DQw7uLTw7eHSxbWHPx7F/Py6V/RyZWHSxYOHPxYGHEx4N66yYV6xxXd+wwWN+ov1l6gv0luZABhnA==',
            'QCkEYGAmgQGgO/nPJPuO9kuYLyL5e+YHhy3e+GjVy1XtW3NX0Y703RftRMlOw+wR6zyw8qNrDOcyrLJSicrlIZCmMajIIReEagGHQyAaZCSdbA==',
            'gC4EiGArgQHgQfptugXqdcIFuknKJaI1wjmSIaIxmj2KLYpFgkF6PXJFenVSKXqVUjFarUo5Wsk6WUrBIpFSvRLFQt0a6TLtEvkjIRshEy0TTQNVE2kLfQOEhac=',
            'MCwEsGApgQHgPRNp1nRO591PPSGDPPyGQPRJ+XPyx+fP0KGqOVCKvPWqK8PXKHEQ46HEQaKTNP7SXWQbibfRcCXpS8STwT8yf0TeCjwUfCnzVfiv3AD5qg=='
        ]),
        bitsPerSample: 24,
        channelCount: 2,
        channelMask: 3,
        codec: 'truehd',
        expectedOutputs: Object.freeze([
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 0,
                pcmFingerprint: 3440316975
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 833,
                pcmFingerprint: 3309928800
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 1667,
                pcmFingerprint: 2905736093
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 2500,
                pcmFingerprint: 95143458
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 3333,
                pcmFingerprint: 2120611621
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 4167,
                pcmFingerprint: 132863271
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 5000,
                pcmFingerprint: 1656457218
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 5833,
                pcmFingerprint: 485789925
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 6667,
                pcmFingerprint: 4064536417
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 7500,
                pcmFingerprint: 3510586491
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 8333,
                pcmFingerprint: 2952319133
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 9167,
                pcmFingerprint: 4216000251
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 10000,
                pcmFingerprint: 2532736829
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 10833,
                pcmFingerprint: 2361293548
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 11667,
                pcmFingerprint: 2996555997
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 12500,
                pcmFingerprint: 1779084996
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 13333,
                pcmFingerprint: 3412960468
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 14167,
                pcmFingerprint: 353080358
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 15000,
                pcmFingerprint: 942675713
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 15833,
                pcmFingerprint: 16664584
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 16667,
                pcmFingerprint: 3921123299
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 17500,
                pcmFingerprint: 120136985
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 18333,
                pcmFingerprint: 3936456578
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 19167,
                pcmFingerprint: 2008911727
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 20000,
                pcmFingerprint: 1209849231
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 20833,
                pcmFingerprint: 2271531204
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 21667,
                pcmFingerprint: 4291289326
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 22500,
                pcmFingerprint: 1455427411
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 23333,
                pcmFingerprint: 1177292565
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 24167,
                pcmFingerprint: 539449659
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 25000,
                pcmFingerprint: 1369213016
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 25833,
                pcmFingerprint: 981034830
            })
        ]),
        majorSyncRecoveryStartIndex: 1,
        sampleRate: 48000,
        source: 'truehd_stereo_24_48000.truehd',
        sourceSHA256: '4ae1dd30bae837f377e094fbc180c9c642a6b874331220d0bb42a6afecd1fb32'
    }),
    Object.freeze({
        accessUnitsBase64: Object.freeze([
            'MU7/sPhyb7oQB4APt1IAAAAAhj8gPAAAAAAAAAAA2hkgZCE88eoAAAEQAAAADq1AAAAAA5KCBL//my//5xAAwACevtjh2vnjf/Di1TB15VGzlmpLwqphbppvkXCiLYIkkDfHhfsRbheN3A4x98ckJBkAAQd8eFy/InVlHeES6PzYgdMQAAH8F4zRfIeR5TydNabp7T9Q9NqVqvWldrFsa5rWvS58J3Xyle2fYiy/OeeaNpLVtJbbsLbNx8D3nxHxvMfKdB8i7lyPuH3vUXkfcvIvIvJ+QfzdwXyeg/IvpeA/4vA/4XgvwP3Agl3x6gAAJVAAAAATrUAAAAACEGILAoIEv/9dL//Xy//ycv/+hQAGwAF4ADYADibfJVmIlTs9N017ipCZImw7fbnL98JUz+dqfrMfOoKXQK1WlhN6wrgdykuL+4CPBIk2/7TU0z4aggSafwz1LRRPdZJIG+PC/xiwC9Kt6xk941wSEIAAD748L0qNeLmm45mLzkLBEsgAANvjwwIIokvnLdwZJOPsEXyAAEm+PDAhihS+kt15km5BIRSIAADQ4s0UCLJNCi3SPJtVUCLpM6o5WPJPNTirza7mYXNKWF7mxpgynb4tbnOjGp5gxsf8Mb1LFbYp8rsVfVbcsdKcVvhZgvcp817lTgkvU2iT4S5pbxPklO0OiZ8Tapnw9mmeku6d+PaJrpBwnPkGie5OdJz49mn+jfSd8N7J7o5un+jPKb5M6p/k14m9y+ic5M9pzQromODfibzJaJXUz2l8SeqVyM8pHAlslMDG63cU5SNpTZYsLarVRLdWqL6qUxHZUnLZvZCmz6Qnm2kL6OnyWDCExszdJX+ni+fxord1cLZdFy9/FkvfsULW7FzNuNIzbnUgDv8=',
            '8M8AAGBAYMuSgICwHZ8R7V8R6X8N5X9R5T8V5P5X7P2T7T4P2V6N1V3P3RzT4NxV2RyNyVyNxRwPvTvNuXtHsZrLrRoPqRnNmTnLjTlNiPhRiLdVfHdXcJbVZJbTUNZPTPUPTNPTTNMRQPKPNPINLTGPHNFTCLFU+LDU7LAS5Q8M6U4K3gAXGJKAgPAaEkBi9l1A1ZeSM02DTddZA3RULOUzDD08807NGIOzRy0MkEc7LBLSRnBT0RklPCXFQwFR0sJAVO4PipIhwVW0NCpHhcVc2KiqHBQVewICq2xAVcuHBWTAeHXLhgdqsGxmKgYJaKhYVsmFjWqoUGcnhYxyoEinSAVNfJBE10cFDYKITQfmhM+AiE0oZQVThIhVKMUFV4p4XVkkhdiMaGWZpQbakGBtucUHXZpIffnliT08kRkpFCz9EoWnqDjMlUwcmqDj1FkohTWJKU2ySt1kg3VdKMYWiId98s7hdIk5XzIueAmbngJmbYzaemAipxmOs64S7XWkvBviOw96C83GU7R5qO3c5Tt321DpxlN7f7P8',
            'kMgAUGA8YMSBCGA42wmgTMmQbIa0TENSS8SgSsaYakaUaQaUSAkgj5nxHyNkeEbg0I0RczIyhGYIiLmSIlBMZCSJD4HmOMdA0xUDyD0OMRAmRZh6EmIoPAig0B7CmIsHImgVCaBSIwJIbA0g8EUDwTQXA1h7DWJwLgvAui4A7gFvT8c5Tfv3BRh1nPY+7Fm/m1Fv3pVee8Fn3GhR/7wYVeNSyp3uZWuNjCzzuaXdtrS9zsbSGm1tJ7bXkppscS2m2FLY6nU1lvjTGGeBOXboU1hplTleyBPWaaU5VqhT9OelOT65kQnyzp2XVQnoslaek0UJ13Ham4s1abcx2Jt3FamG8lqZav3pZjHellrt6SXwZJNK5evK3skgjZzWULuS2jX0VjbeasfU0UTLWigZR1ek19nhlHRsRR5bF0dGIk/n+ZO2+BTePBUvfqJK35jS+NgsXjcNK4yiwt9A0fq8JA3xDQua4sHa2K+5pDP96QrriaQ+2lDtuZBDzaGO12hFN+DhDXU6ay1Kktdi50DEYQ==',
            'cMkAoGA9YMVgbBmh9GaJ4ZgzxljWH4M4kwyiayEEkidFFFNLMV4yxZjfmmNMdc751kDHlI+RJI+SrTMmUpWo5YmpZeta7Ba92S2SmqTP3KNr7tNw71J6t8p+ihPATiqhpSEoqUpKSnLXMSmpzl0kU9KmlTTqJ1krCOuu2isJ3oDMgC/UkYy0Hz1ug+gvyGUVeo0gsyFF1eAqeozEm1N4gklyD7amwOLosQ46mtDLSK0MPI7Qy8gqCkKKwLwHqQpIgqCkh2gJynZwrOdoCNBqMK0nKAlYaiClhqQKWmJApgbgC1xWILZmnwvgUfDOhqAMZlHA5uXeDmZZsPdFWw/oWbE/SjQjqUYGPSrItwTWGvCzA70TVIeFFSPhVQt4TVLdlETnpZU32SPhdl04XpU+R2VQk9FjpvhY+hwYOqeFjq3Bky10XOu7mC8PBozHsZL0bGzNehwndoaN4aHhuuB07vmdF93IDv2J4VjWjMa3IB21aQt3QiIeVJiX8yQhSlTlqkychZhUFq8asldgVErr0IHy',
            'gMwA8GA/YMiBAWA+becGbucW8FsfsVcvMuc2M+tGtd8/d99Pd1929m+ON/OGOW+WeXOuOW++ume3O2O/O+PPO1/fe1/nO+Puu+/2e+/+u+f/PGP+/Gf2fe/mfmvWfuvOfufGfmfOfefWfOPOvN/GvGfF+2u9+ue+OeOuOWeluW+NOPOM/UMsMSD6slJMsDEk6tISq7M5MNMCUsq0OTSrUtNqtDkyi4OTyjgxNmuEE8k7NTpjtFOovT0RIfpJpF+eiI0FNOHQkE4NEWTxMNJNESVU4PDUTA81dNDRV0uJOWSpEltKBUFkmRMcXxKLSSFourI1FpeEqwKw9JpYErRqZNd1RErxPiLUTsezC6JtStBrkLQy7R/HvQ/zr1fgnDH4QwV8isU/FLDXtOyVaUcdedTLZiQy24GM1t1LRbWay4WldV853PfTY14yX9GMtzZnDh04RX9m5yPZefi2blptmJmXZyTp2ZEaNvA7Vs1HrN24vVs3Gcd2onZr5Fct24fw27iOWzkO6beA3ps2Dm2zoL669QxxAFQU',
            'kMkBQGA8YMWBCGA77kt6e99aLa2tFqfUnobQizfmR5PyJYl4mwJYWuruvceyq29dVhq6qjVVUmotRed05czJaUu465PRfivEuEuDcB3uvvec5517i27NMa605lbD1+MNWarxZqi1WpbUaktJSPT9o6N2isziCDOnJL2aovReYn5s8DGuvMJ+avQxpq1CP+rgL66eQl/q1CfGjkK+adgl5l3CnenUKeZeAp5kzC3mfYKd4dQz7mzCvd/YN95Mgz5e0DnGLIOe3MRDjBkH+bmItvcwEeLd41rawF97Fg7nZuHN61pTCtYP506zeNSorbRpP40qztM2aFhQojUTZ49UuSZPLnnUSYaUkeetLIfrww5LsMeC9DAfyOxIMj713WzDe2OvHeLDxrks8c7sOWvKbpr4s2YZIt1/6LZhyiyUbHNV3qDBJ8UxXUUFyCmMuVVkFp6wIrUWzVZ62KpQSRShBeETmpMhMglhU5iTGRHpoRKWliEJqbCRGJohAYmw0BaeGPFpoVAUnxTZaeHPEp0WAPQB',
            'UMoBkGA9YMZJSy5kqKSSokZCiJjrIGMgfQwYyhhCZGEIoYMNIuAxCJEjCwJMKMRQQMRIMQkwRiRATEjBkGIOGEkOCC0FBiDCjEBhjEBCDDhiRiQxJChCghhiQQ+BQIgMWIiIeGQERBkyIBFgyIy4ZMRkRYIyRkEZI4CNGfAzsAAcrBwpPkGik6KaJTpBopPEmCU4QaJThJUlOGGyEySUKTRxglLGFiUweVJShxcpJolCUkiVKX0ypK+oUNW1SxC0uSNVlixSoyULU2yZr9osW8eJnunixTh4og0iKGMoiyX6Usb7iKJd6jCHWQolxsNI7qSiWus0rouLpY7TC+LA2rcvMLXNDjFXEytW2PMzsjbc7c8xK2OvR90LMPc9BC6Qtm+UMB3lC+W8TPlukURLxPAQ5TSDnyeQb5Uxi/ymYX5VTiny2UR6V0iPy+gPcsKQ58vqDnDOsL9saw1y2tC3TS0L7t7Qpy3wC27mwJaO8Qrw6xCWb/AKavcwnhAxCej/MKXw8wnfC1Ct0bILVxNwtdAAMs4=',
            'gMwB4GA/YMgR4EhGhCRhpBpQaUagJOGrCUBrA1oa4NeJgEzEyCaiaBuA24boTkJ8N2DfFABwRQRxQog44UUcsOQKaKWHOKeDnnSB0ipiqirFXB2ItBWzth3iuiwneDxxhDylkLKPOWYeqM4eutYWutw9pbp4B7r5h7q6D5TzLtHGPMAAqMFI0DE8bQLVzOA5NIzDM83oOxzMg/JP7D0M/QUhocCT9TgYfobizljgcbpcDjNncg1W5JK29yjNjg0hc5MMWtoJ1/o6pb1jnYu4Z9zKcfk7lF3s6Z2XikVh0sF597ZOLS6Vn0wjZdcpWfPMJoz2E5s9oevPmRoy6CacfIurD0NpwYC7Mf42utuLqyai7qXg+vB2JtoUB9lyiPsnVh91isRsoWidk64RupXjNcS+PvqSSGuJJj7ZUqnthS5OqRLp7n02fpjTCe51Oo6IE2tudTqeZ5Os7nU4tlaT7OtxOuZWE+1qbTj+VZPO52U5DkVTkWddORYU01LnXTUt5JLT5FE1TfRSdOFJK13kklbeOSF0ANGd',
            'IMcCMGA7YMOBEGA4+Z+RdN5C7X0XY/Q/N9D8z4fk/s8l8vsvn9D/bwf++p8vzej+t6L5/N+bxPr9z9P4Pw/m9H9zkv1ebdv1fluiuW4Pybc3F9v3L2/Wva2hW1WR9asas75F4nyLwLwqvJX3uJ3V2lWkq67KqiKwqgnWgJAbXkkhbaNWsrqK3fYLWNLaCrlWMVNbBqlrUNe7VSnm9M1xvTKbdTy2W1Ipj5NL98zifXcszr1MH6eSjd/UcXd7IOz9xRdP0c29zBGyfQyrHcEi34+Kp9PyKnjwuby8Jl9Oi5PTkmJw4LhcNyj+zMw3y2LM6MTS3DMopiwPIarix/JeeN4rDRm9aeMYKThStWiJXJzxKtSmH6UiIdoUJBylGmG40igYnRqBmBAsFZEagXfOsBR5EsFnjbISbPNBR04wFFjjoSaONBVY22ElTD4WVNthNEvCFkzDwWQMQhc4tCF0DEQZNKSBswvEGzCs4eKKyB8otMJFE6BIYtOKllKxcQnONkl7RkQjSSIL2Dwc1TA=',
            'UMsCgGA/YMeBAWA9Z1qWJ1J2ZdZl5FpV4to+ItoeId4F4GH2HtnendXWm1nO2VXHGFWW2VlmmWFGV+FGldk3FN0m010e0d0G0N0GzmD+TOj2DGzeS+jOymS+ymSuSOymh+Sex2CHBtx/Bmh2BXR2BGhuxNxPRVw+xWg+g2hOwdxXQlw8svoRtLEFrCoRTA2OUtOCFbzwxbGKOUxhBl8JZBTOSIXyokFs6IpfOqSX0tDGtbZRbTEQa2vlmddRZvfOWb03nG+Npp3bscd46Intvhx/j4of4/ooOGyyDhkol4eMIOXDCbZRaSdqDSbVTdUcrDqbdWgWcLj6ndbkV7r8C7hJTrNUhKy4S063ZKVNNUxUv2TFLbRMXs9k7Y3zTeLjNN2uNE9o6xTmDzJP6O809o/vTuj3JPcwr07nBvT/kO5N6w7073HqTXMW9NdyJ01zJvS/kqdL9S6kr5OpSfkyZI9UaUh7OjXe6k637QjWuq8it5RiVu7UShzVhUvLMDrm0897tQM+Lrbfe29/6vt/9LrXriCE4Q==',
            'EMoC0GA+YMZ0PYJ0TgFoRoJkJoRkFoToHgPsNgLoRkLgPkRkLcVoNkVgRkXkTgXkVcdoVgfcXkfgbgjcdklgjcpgjgtclczYpkzQxozU1c3Y7c3VBY9hFQ/hLJBlTNDdXNPdTJbhRJhhXJjZhNlVnRpRtNvRzNxR3J5N5OBJ9SHAAJJxYG/OWFflric55YVNuWNrZlkUzW5WMmWVLFTnWt4Zk7s+dKnZoUrzaD5tGlGfHoRkSazZEmlKC9rMgxazjrew41BsMMNazirWwokxtNH2NhQ8tuLGlthYyluLFlNZAmhvME0NRAfQ3Fh47YQGzNpIdO2FBgnWSGDdhIYH1khQnYSFytJQVE1kBMzSWFQtIwSJ0GhQXSOExc5oSGzkBYTOcEhshQWFzGhUTIUFR8R4ZCyFBYnAeHBMRYaIwIhwe8cIEXzw6RbRFiL6IgXXQGSbyguZVRGzLig+ZTTHT7CxQ6mmTRqMm0aKhdGk1BVnrnk57Udie1FVltzG5jk1iU5QdjvVXJLtV+NBegiQWoYAkNw=',
            'IMcDIGA7YMOBEGA7wfEXE0dorTPGaf5LUNNaj6Hp+nq3raxK6rhWXu27buxW7ctvzPsRZ/mLPtJaLtPTNp7ZsPge6by5zcXct59i5F2LsXQ/IfWeg+xei7i9l4H7F5H6L6F4L+H4L4F7L4D9n9B+R/g/QXwfsL4H6H8gADc3RYMkUCPHHDh0zPpNcsCPbS8m60vZuVLmf3a6n9VuJ2GDapha2pa4s7HGbSh1gxwebMq1HJdepbsLFXdXir6rb1rlXiucKL13lVoke0+KR5TZJXxNok+UmaZ+SapblHqmf0Oib5RcJv8/knekPSb9O5p/s90nOj2aIemu07ydzT3ZrtPdGtU9ya4TnBjlObmNk5yY7TWpbVNbGOkxmW2S2pbtLYFtUpmU5SVxbhfyK7JCwput2lt1uwlqsUl91Wojopyl91Gklo9iK7PJimLaErs5gKY/ny2TR4pn4dLXfGS+nR0pd1VMX7my1+1EvZoaL4ZzzVWFYvdgON020TFlk89TTNM0UzTtM007NLKgJME=',
            'sMsDcGA/YMeBAWA5vLPhvC/h+6vqOqPiOqfB/Ceh/CuZvCeZ+Z+ieJ+R+J9yOJ9qN59idh9Z9KNZsytJcic5cacZsacRr575757h7h7Z7KLJq6apKy6JKiqBqJ5iKBZaJR5R5J4yY5IiohoJ4SHx4CHaHpnSXRm6m5myWaGiGCGR1yV0xjEeokln44hB6eCUiigDn4zRCSM0MggKjpoSYyR8kKlfHB1L46GlbFxlj4wKnZFBFzomOqXEQl7YeHXMB0VeqGx2bQbGYJhcduuGR2KoVIcpBcpqqFR3KATNcphUl0gEkHiIVKfHBFJ8iFDIBoTUhnBM+AeFFI5oWThGBZaUcFl4hQZWmGhhuQSG2ppobdljh9ygcHoJo4m7SLEZZ5Qw/VIFqKRg3DVFG6axpCmuMRotGlLK4pWu6abusDG7r5kDG2RCwwFxcrxUnPCRM1wFztMplXe+VT1zmXOMJdnjQdj4yF3+852rjObm90I7+tBe/vQl091Hd+tafn3Sf+72pf/dCTXveo08zqPPeCjrqAAdww==',
            'MMkDwGA8YMWBEGA4S0GrEpBqhJwacaYJGGlDQhIhIAjwz4M4Z4GYI8DLGaCLDLCKiKiJDKjHhlSHBkoOCHwaENg0QwxgxYxZihiILEHgkhBhiEwMQaCBg8JIFRJAqJgMw+BmIoOiDCcMYjBKJoTCcGwrB+J4qiHFwQ43i+Mg29xrVf+bFlLreqpdaWVjvksr8Z213nkwub6HF/ng0kc9TqS53uJW/U8leN76Yv0QJnLhCmL9MCdu2ypq/S+na9k6ds0xp6nTMnKtUqIS56U5TpmT8GapOy6KU7DjqTr+etNw4rU23lsTTuK5MN4bEyxiySrGC1Kr38UmrevSSl7NeStYJBK9osoV8FtC5urm1sFQ+xuol1MlAyvw7Jo6OzKe7Ualq2Mnb/xaXH8qXt5DnceCpe/QSTvxGl9bRo2usSN1nGj75BYPGAaLxeEf82RoO9YV/zUHd7ThYHNAhvrHHe8SCWnEEd3pBKacnCmmZsprsWOX7FSmmZJFZsPlssx1NZmMHLcxpNXiKJqtBRWAAFfS',
            'IMwEEGA/YMiBAWA8Rsh0RsSEx0SMx8icSVSkSUy9CUjdCcTli0jtTUzlT0ztkMj10kkV0c0tk1VFU9VV1k1l1ll1WOF9GWWdGmG9m13FnWHV3dn+HtoOYF4d4mImI+I2JN5WZV5uZt52aV5/Klam6l6+q97O7OLmbeb2r2b+cGseMO8kAYspvEVU+IfWTYB9tReHF0doZcSXBttJaF30NYWeQ2hiBBSE5D9YWhP0BOY9SFJTc4UoPzhCgxMF6j0wQrLxhWw3KFbzMATtLyBfE08FcikIZyNQBfMo4GtS8Ic1LsB3UnAHuC7AlqSbD/hhsY1ILCfphob3IrDPxdce4IqEPSyxPoomW9KKF+yqR30okd6KpQvix8LomlJ7MHyfCp0/ssfQ6Mm1Oyh1jg2ba6Km3+DhmHcuXk3Nm68zRGfc2bzyPEbtDRfjA+T2yPFfsD5XyxAS1uQEsrEZLutGU4oRDvqVBShKiIVJ1JanEmIWpFRSxAoJXoVpa48pISTi8tIOrS0oywJSzLAxKsMzE0sxLTK0ADn9',
            'ANEEYGBEYM2BAWBGabNJqozT5qNVOKrdXqszW5rd2Gq7NjuwzZ6sc2nLO9p21va8tsW27fNvu5zb7u82+rzVxm81c6u83nLnN9q41f5uNYGbfeBi43f4ueX1rjd9q5xebucXebrFzq4xdatrXW7W1vu3va6tcW2bK1rqyvYZtbVurK9bewxW2rc1l6q1XLURNzE0kzNTajo1OJNz06e5MTiDw9Onu0U+a+OThj5JPmwT06Q/VTpsVBOiQVE2ZHUTo0VRMDyV04RGVSwk1hMEyF0qFPZSo8xpIi0GUkLQeWxaDKQGqPq4lN1aHqOqgtiFVGqvvSLUSkNYibD24XhVyVkRajaFYJv5Nub2Zjm9F3J+p+OnmXho3p4a9ZmWnUpjsyI5rMama26rlsuq6MKzGiyqxnyoNarp7ejKU7sxjvZs4r+/I/DozhR7szEWjU3NvzKS6didG3UhVt2Hqdeo3Zv4GbtWgtXw7Fs9eYfu2+Cee7MPY6vA3rv1D2enoL779g3pq5C3WzgL6a+Qt5q2CeurkL/a9glvo4CfujgKdQDsnA==',
            '4VIEsPhyb7oQB4APt1IAAAAAhj8gPAAAAAAAAAAA2hkgayFA8eoFAAEQAAAAFK1BYAAAA/SCBMABJy//yg/v/QpCI0DZw2BNTfLiBKhI5HXRbBTGRfMPe4cu5o4rA4GN++XxCSSQN8eFztIblmXd/S6bzVAdmQAAi3x4Xikc5W9NzjMNPJICGxAACNcWiELj0o9cpIWuSscuYqeserApCtI2JWZ0jqXysrdSyxljLu3Nx7d/XePtuZ843vznPO/cda/v5lnH9msNUbw5N7DslV35KqK5KprYrpLYpJ10UsyRFLHTIpY6adPHTCosZNKjB0QMih0WKjJ+ivHqBQAlUAAAABWtUYAAAAIQYguuggTAASkv/8rMABKy//yoaMXlGuyayzytxRA6jIk9FAhHkwFibp2NshKZlHHn4FscsUGIVphuKc+NGE4Y3QtKI8JRkdsIwRo5eWt33QhCjFfgUjFZ1uwBCTwu81VmdZjbThJJA3x4XYkfQWtN1UL/HK9B/JAAEPS3g1eX7UgwfS8gABDvjwvb4zauqriAY5eP+EVSAAIe+PDB0iNa/3tzhkW5IAQ3IAAEFCTcIgNEYpxpt8SEn4kST7wkSdgwGn3Z4abeHwn28xJtwcafaXElWZ5p9fckmvkSdU3JKqbklUlaSqTY0mdtSRP8NfLbhfMbhbH+xbJcJXEf1XGMGpge4phHLee/yofW9bdHKedW9Yb3pbbnGYaVEeZXW8yqs6vvbldWdxbUdZXV/hVV/VRW9VQWNJNXKmmLegkLngkJCjkNaxqKlOagr3KQktMo9SOJQUxEOPEhiT5MSFnaW40+S0Qs6TFCz9LWIO09MWepSw8+RCIQeJKw5CRKQcepiMOQ0QsMQktINQ0ShBiOlKC0ZFoQYlyNvQ==',
            'gNgFAGBKYNSSgIDwHZa1+5nrXcGGxfyX7F/NbuXc129Z0XcVfJd0VcFvZVxVdlnJR0U9VfJN3V8U/hRxT91HJN2Uc0vVPzT9UfNTyRdk/FFyTdEe9L2R7kfNJwR8EXBHwQ70m1DwSbD+1JuP6Ue5BnQ7EOZDqRZj+dDmQ40OZBiQ40GNBeQYz91DeP3kNw9cQ2EFxBVQW0FOAJbHkoCIcIYhwISVhSUi0MNUUlQQmIpGGKyajClNNWFLKJQgxaSkwlgRKYaupSIJaEQiDWRMWFNqchhrWmOGOaYjDXNMRB7wlrDHxLRCn5LTDINJSGQiYiDopckOjU1YfHrkx8qlJCpRc4+bSEQ6dWrInl7lUqtIqlXqKqVKjqxcs2uU/CxVrPs33laqflcqF1t3epfKFYunNrhOL3eO7jEZ7uA03MRrP4f+9iNc1jctnDZ9vH1bmGxb2NjHsTmKMPVqcTMqb/GrMO8Kr61r76xrLutpF1E19za0i2PJKs6QkWhsplZIkqvOlNqDhpdOdCbSlkm0Bpps+QSdOGjTZQcSImSyTI0eJEyI8k2IIEnxAwafCWRD',
            'cNYFUGBIYNIgroaZ6ojonaSOgfnoJyGaflopqCOgmI4h6UkhH4yOGggpISB8kgInaJ+jcI3qJsldI2qNqmbomKZqjYJmSValXplyVWnWp1CZUoUJkqhQoSKEilIoQqkalArQKT608pOrTio2tNqza0yuMLDK4qwMqybMwtKMia8sxIMijEkyIMybIezItCDUczIthsAAFLKBAeEMQ4ELyTX5UCRD+tlNd1QNNd1g05yUjTXBSGltKoSa1pw0pkVCS2JKJJXlQaUuJQ16ynEkrCUNcophr1NGDWJyYa1MRhKkxKJYjJBvJCMJYiJSaREYSlBRkyhIw3j5ITB+hCaPkxsHiAXT1MLp6gHs7Sno9RFo8Riueo4ufIx0PEh1QUkSP0Y4oSWYISODkVMM5HS2ajpCKS09lJaYyVBLZCgpkcppZHrCjRauokauqMFLyqxbGpsPZlfCmZVge3LLDmxZ4h0V4GOq7Q95XeFvq7g6AY6Fwi9guFY8FxrLwyKYuFSrXwqRZMGTLZIKmmmhc63SCqNswZROVBdS4WF1DlQXWu3Dq90iCbF64i0gMm0=',
            'MM8FoGBDYMuBCKA5SJBkB5R0BpxsB0RcSERUiEhNCMhNB1BtBdR9xlB2RtBuh1SGxlyGx+B3CWB3yeB/iXCPSnSXynivijSnTDivzDzDDLjLzbzTzah5U0qiUNro1TyyRdAulSo1kyVKmUJFCVQnVpVaItTrE65EYIq9EZIzJEaI7RFbo7ZHdIzZCvaNpYEB4QwGgQ8WJbP0RFy9YW5gox718oq9hoxr+C5uFCREX8VM7FhrKwoqI7Ejoj8WMkfiSEaWNISPw5KJbHlokMKWtjGmISmDMSaxJ6NbBlqcwKaCZvZanb+qjfupyJ28qopLSgk9cVkU1lTRRWNRc9dWRUVdRFNVWEq6SslTTV07Z6ylbPWE7ZqyljLWnvk7SPORtfjFWkWkZcfaDtpZwt1t322lw+3W3d7j9u15Llwu9033kvGm7vbRdf1kwN2w3G+XsG+LV1X61fz5Uut6qYO/UL2/J97fku9nyVe/9IvX6i3d+Rbs/oV7fUG5Xx/dvw/uV8fXs6PbZ/Htu+Dy5Px5anY9tz2e2i3PLV8HsP3j',
            'UNEF8GBJYM2BAeA9hzXe231Z7ch1n12LXgXI9mHbkW49yTbk3plmXgm251yhfo26F+nep3at+rcrYbF2vft37N+7gtYMN+1hx37mDHhxX8WLJgyYcuHLg0Y817Tj04NWLVf15Nd7bj2YN2Lbg4YtmDlj3XuGTle4Y+V/jj5XuWPne44e2Dlg6YOuDjf74eF7xg44O9/le6wIxoEBoQxDgRwNcf8wtO+CXIm8qTzYSxG3NSgampR9hPI+kKEnYTSViN9OzH9QzJxRvF5WzGwq2B8XMj8t2A9MOB5YqgWWi47s9IOzfWOjbSKjtQHF1nDi9UDPfZQjoGYR0HGGVFSiLiIgyZKMMqQfDGysQx8y8ENnXyFzrwMdSOEJo3BCalwQqrZEH1bZCLJYQdYtEHWygg+2ZILuUiDrpYYXeKEGX6Rhl8mMJwkJDcJIgnCPgLxDjC8VEgnEMsOxjyB+GXIfjG2EYpZBuKXgZhFSFYpNB+ATQXhkWIvicC78ehd2NoZek0LtRND7sfhliLYq2G8ZWCaNsRWG1IVk1IzDaQNjKODwgQ==',
            'wNMGQGBIYM9g6XOmDnc63+d7tc44Otvld53edzhc6XOFvjd5Wt1zla3Wt1vhZ12uFnVZ22ddjXX1WdNXTZ0Vc9jNUzVstXHUy18FLHVw071TDQu1b0+7Tsz7lOxOsUrEytTrTKU6tNoTqcufPnSaE2VKny5EqZJjSpMaJLjxocmHFhyH0SHGdxYMNzGfQ3ENzCcRG8AAYe6BEOEMBoEBfIT4Y6s2F8pNBbrSgYpiTCfVjw53YsHpMRAb70IEqcgwtKB8DHfewlULuGLidAtKVvC1SNwYlO0BS52gORUsIUqphDU610OTtWgtO1WD0sFcNTuTw9PNTD08EoORapwelojikLRID17owtHshB6fKGNT3PxCfaGMRcHY1PtBFpdnQ9C8PxiXZ2Qn8eDUL08JS9PCE/j4tP07IRfn5if58Wv5AMRfIRyfyCYv9Gil6hnI/0qLeo8U/U2S/k2b+KVEXihNvFm6fStX/Vy6W67lXrFj9GPa/GnH5tHV8N/Pzcetq6+/J382b2z97//8YJvroRn7otzK4ptrJB7KJNzKpd/p5iAAjTI=',
            'QM0GkGBEYMmBAaA77WRq8zjZvMIGT6x5k+pdXPqWlj6ddS+oYSNp20K6V1EqgaRLHmD6p5g4qeVMrnUi6x1IqoZSMKFUC6hU4qmUOKIkjyRxREcWVQGGEjiBg4wgaOLHmjiRpg8oaUOKFkECxQxAkSQQIFDjhxgwwceKKHICixR4o4UcKPEGiERRgRIYbP4ggQHhDAaBE3JZ+lUs9O2Skp5DSUJiq6ePVNOX7GpbtdVlq1py7aWbXt6ZNXVqlburK19aGpe1rTwbYksGxCOHclHDsCNxLxn4lgZeLfM3DsCKyMBFYVoisa+IfDtCJw8Bi4lwIjBvELg3gxb+6MW8wDEvrgQdzfEJcXhCW14QVpfEHY3QgrDAMOruhA1d8hKa4CBpL5C0VwIGdvjFm7YMKZvDFk7og5O2MWMugxY20Q8JdDFh7QyX+yEQ+3CJerBFOlsMp1rDLbbZnNtQMtotmizUjMYbI1GKkM5Zr0suUQ0FOrLKvRNRPpmyoT4YTKctJcyXEinDiNLp9Fny6hy6jQZsvoMu5T6AMqk=',
            '4NUG4GBJYNGBAeA6ImkHIyiEelKHyKUmfKJSh4okMHyaQ0gKIDKMygMoDSI2fNozx82gQoTqFAeRI0JxGlSHUaFOgSoFCFQfUoVR5YjWHVyJYgZH16RkbZJWp1ojbH2yF2jbn3qNygfoXqN+fgJYR+AkjIYSKOlioZSSOklopaWYjmpZ6OanpoqCikkqJqqaqlrqaya2nsRi7YEBoQxDgRVHECvenc9Mn9OfOZcbP6MZOpMdPZtdPI+ePY+UHsOKD+P1R+9qo/hUrQ3sXIb7rENxkhIcdejuekJTLpCc26WmLrSFNr01SWUlK6ySasLumrqa0xeVWnMaSk1jSTTmlJk9sQRpree6e4ook52NUnPKCNOfDHRD+ajTIM1SJhy0SZFGIk2OJUmyJiEmyo60uVKRps8OkkzZSJMoxVr6EhCS6oZNfUCpJFaOjXVoaa20ISWWIKNZcDpKrYNEpvRElFwIiUYIaTt4GjdwhFOYIKJvCERMYoTsYISF7HEV3DBXzFERaxwVawg0r4wj4wwk64Yr0wwlzwBFRwBlSwAlm3g/n3gSjLmAABTW',
            'cMkHMGBEYMWBCKA4HuAtoD3ga4CYAa8DYQXAC4guMFxhMoNkDZgfME0BtITOG2htAbYJsDaxdofcLtE4i7R+InEu4XoPvLzG5H4E6m4F7H4Q7l4T8E4V8G4S8T4w735H646R53605W7X427Y5X6Z5Y565a5a465a4+354+3d382t362O3d1u2e1v1f0wAL1zEOZdCeXZjKItR/IsBmIrxtGVhLjqgbhtOVwqhI4ZRlYImyvFTZdh8uTwdJHWJky+Cok6hMabQXBn8GQh5hz6foU+I0GvKJhTklgY5pwFtichTWtAW0JyFsjBhLCrIcvsDB62xActMwEqbgg1WYMMTXYDVJ0MNSHDDU2AYhFcMNSIwxKE9AeiSBC0GAxCBKIafxhCz6Qxp7MDHHs5jj2cGSd1DIPKAZR7WZp3SCKPrCke2BFH1wqINgZ5/gFVDvKSHgHhFxB0SMi2j4h2TdRdS8g9qOw/KGYuqvAmljML6z3Di5mGywdDeYuA3Gfg1DT0NQ28jUN/Y1jpySp28Na+QG4j',
            'ENAHgGBIYMyBCOA/mnbR7m60dZPsvOVjH1jYw+Yf8H+D+7/eZuf3GrDNtmw3XasN026zlJyk5Sdnuz3Zz0x6a9KUSnpCiMokPw1UV+GqgqoKmAreqnyp2sdqXa5wpcL2ypuuaKma9krYr2K5asXr1q1WvWLVCSrWJkhQvTL0iSmWoExMsOpSVIOL0KScST642mHFpqAAnjt2S577NZCeDSoH2VkT4aXGemkR3spUl9CZK+ylTP8Jk59SZO/UmUn0p1F9SZV/0iKj3Euv/hE1/3ptn/Kfae4nW/3Ii5/1Mu/rRN56yXffYib/zUvA+ZPw/OSsH7U/F6dfhfeiMfpS/E81NxOlr8Xp0nG6dIwufXY/K19/u6zF5SWYG3rL7dEowdnVXOyT19opRbapN3OaTtnkk1a5pN1uC/2OKL9Ril6qtS5SYIvUVi70FqFybtSpMVJ4l7EVJKdOkdYnKOkRxh60oQsSI+CpSLfI0I97lTJeIllOMaGU5QqGtcKMpsgRC2V5Y5jfQhbC4kKXXEhi04iDlhlYpUaRCFNlQcnwGfA=',
            'wM0H0GBJYMmBAeA+M5fL4jWEvgL4S2ItgKYy18liLYiOAnhJYiGAliH4CWEbhJYBmEjhHYBuAhiF3h+MXeH4RV8hgE4SFwTjI3BOEfdGYBl0deGXh14dcGYB9obfH2x10fdIWh94hYI3SNklcI2StohZL2iNgxYJ2C9gvYL1y9k3ULWjtEzbP0DVk/SO1D9VDRQVUdFDUSRO4oEBoQwGgQujHTmXFSlEQqSuoVHTTERVVCIiSxEFNMJBRYRBRWCeIqEQT1BHSCgj81wzw9gjsthD05gjslQh+bwZ2S4h+Top+Wwp8P4qITYx+Q5CMPY6IOxCQNRKSLxSYNpSeLRicNhiqHpyoNByyJiC4HaC4NCbGDaLCJSzSHKbQFLLcGaziHTLoETbuIbb6FTj6GOCECN2FDOOHEKGQCKSLDKSYEOeSCDmnhopmAQ6aQgq6EIdlMOKypEFfVDCvsBR4V44s7QYWFmSHtcjlpcDhbXhQtr0gPm/LHtfFB9YRgfOEUH3inD7wSwu8hAL3BLPzHRC9xDwvsZAvcSAl+Q=',
            '4NAIIGBCYMyBCKA6VKmSJU6VOkUJFK6tdWuuWVqsFV6rFRkqze0UaObvbMdPcfdtdsffefgsgdgfhcieh7jdjalcj5mck5nYm6nXoYoWo3qVp2qVrUr2rys0tTtUuwtUwQuQwxvnwnxQxlynxFzlylzj6C5xtRNQ2kbaNpG3iaxNwu4NsF5BtkAAt9CBEOEMQ4EEiT8UkJMwTBonGKDTb04k/ELGn3cAk3CMhEXMBJl7EkRbHBplxWE+ygNMs7DTa+UJlbcaVU0hNp7mvpcGmz9zW0HIS5q9K5j40qVziqR/C+N7CqM/quGYhTBsW/AMW+/NU+7t628tU43v6y5tY0zqc+3N99hVbxldzq+r/K0p3i4payos7Ksr+igsaqgueSYs6aWvWekLvgjL1HIqQ5qGvctDS1Fny9ZKGmqIOl6iENMUNOElIegpihR0lrGnqakJPEpIUdohQk/SkYeeIhxJ+lIQafp6g9ATUIMQk5QchJyIMRE5MMSE5EGI6cmFpSamGJqITCUxMRhqoiUghRSkYYsIpMKV0pIKXYAAmpY=',
            'ANIIcGBJYM6BAeA63mw2rOa/et5q+C7qp4reavmq6K+Sjss4puyzon6Keijsn4qfCbin7J+aXoo6pOSbql5JeiTil6o96boh4J+R/im3oOaXWh6I9SPig2pdiDci1IdaHYg0JNZ3Ol0ncyPMgzocZ/OjwHsyG6hyH7yK+fvobaC8ftIrZ6wisn6x+uiqHqqOieqIJyKoelzW7CehBi8nJBLElogxlRKQYzpCEFtiKWGNy9EHOSITDHZJTD3dNRBz8kqEPyajD4ResVCpqYiLXJC41LRCpBe42VSkxkstUPnV6Y2cXqLo1ixtEuWfUK1kVS1cKtT5dgsSjXv+fbq1Rs3npdKHpcP7a9dXe9dy984rWG5ur5ru47jcwPZ/Gb9jD7jOMwzeJ2W8bzuYepfx+6/haxRi4tThbtXgVpVhZpdeVtZgVlfb1NdeytKtqQvtpGlWp8pdfOEmwMhNqoCSqs206kMDS6Q6U6hIGnTp0J02ODTZc00+SGknyRIk2KHknxowNOgSCT4cSNNeyAk6AEEnOg0ac7igaW4CjRDcJBpLZG3A',
            'oNEIwGBIYM0ion5SKaflIpR+Ojkn4iSOghoYSOEggI4CN8gep3h54ncoXCNylaI3KNgmbImKZgkZplaVkmUpFyhSlWKE6ZSoTKE6hIoSqEStCnRrDyhEqNrECg2tOqzSs4uMqjTAusMryq4yuJry7EmuKsyS4ozIsSbIezKMhzQizINRzQi3Gsx7Ye4GNSLgS4INxkAAMlaBAeEMBoEKC9ZlILllUH4wpgul1SFuuJi7WEoPRWTC5Ukos1BKHunpQ80pIWSWjB5IyYV6OhLJETA60FAWKCmDpQUIrT5GOc/SB1niEcp+mKg6QCkPko4jtFEh6hDdPEpRnqGGz9MN89QG0gJzZQUBNoSelkNETCOnhRDR0ompiUR01oKCU0kxPhysmJBRT4asKrLWk0nLirSmFVZLCospoW8M0KKIbV/DuKnhXBfoz0s0R3X8NAMGDfluCw7NwoZhwcYyUJHM+Ckmag5Zrwcu0WHPNnCnXDCUjRYdI7YKobJCVTtw65ysWueqDtHSx7OAkHcPFk3MBYdy/TLvYKxr+AmVfREicGCOwQ==',
            'MNQJEGBEYNCBAaA7Y1UY4NZGtDHBjQ9wU8QcEukHhjo2Ae8MhHvjoRsBGIbEShHSEoR8xKIjMTlISlpyMpakpOXnKVGKC9BmwvQcsMVnqjFyCs5cfsP3oLkN6G9LeixTXJMlN6XJZklyX4qNl2C7VZozzW7NdmObTprk27b6OOXXDrZ7084fcQO3/EPyDIdMgQHhDEOBEJIZhRExOFGSHYsRENwpKZGNFSH40pEThyEy8aUiJxZSZ+JNTKxJSKWHPRG4MxOeFPRRvpyVcCkhTvJqV7yojxcUE8XFRLVnTR7tKi+11ZH2vqLYqa6JiprrapqqNuhtKboa6b83aTem7KSiTsqflri1kXYTVR151kPYSXQt9SuCtOkPt1JIfbzL3W26U63kklxu8ltd5aW2X+SmS6pOZr3Ja5fZOYrrJqtgxNW7jIhTxamKVrkQoYeTk63aclYdRCTa5LR8FIpGu6lId3ESg36TEK3aafYMT0CzKUe3rTj+5SSdWoTj67a48sEmnl6Vx5XpKPbY1p7YlegWDWntkliDXNYg1oUIdcNYh1odRYAnGA==',
            'kM8JYGBJYMuBAeA9iLciWo1yNZlXo1mddkXKFuXfoW51+ldo3al+ncq4Kt2zfrX7d6xht3buC1hw3beHHfu4cd/BiyXcmXJdz48mDThz4NGLVf0Y9d/Zi04eGDRj43teXje3ZN97lk3X+eLfh54OODpi43+mLjf6YemDlg74eF7vg54Ot3pi63OeHvc5YOt3pe6X+Vvrg5QACoEQ4QwGhIsLEYWh2DCubR1YFWOqjpH1IVhRVEhNQHSYfFGcUlKcbDhhqA4oDA4JagJ+MyNyk0G7MaDaseJqq2DYu6GveaCWw6NTN8DU06NHZoJPhwM7lYNHxsZneoZv+wZv6xFM5hluKhkNpDKfRGM6oIlUNGMoSEMrnDFVzYGWDgg10uhFs0MRIEwGvGDESQ+QkkWMJKDZDSJMBpgcMNIjrCTAwYiSG4ElhcCJUZIiTFyGlROCpAYYqUD9FXhUjpIOsRbE4UuhuCLQnTVgNoVXDuOUg7CVQNY58HYY/CvPch/HOAn0mgjUGIQpP+G8n5CWW9BzK8whmeYetfaDua1QAAAK'
        ]),
        bitsPerSample: 24,
        channelCount: 6,
        channelMask: 1551,
        codec: 'truehd',
        expectedOutputs: Object.freeze([
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 0,
                pcmFingerprint: 390862353
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 833,
                pcmFingerprint: 2241950691
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 1667,
                pcmFingerprint: 1126270315
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 2500,
                pcmFingerprint: 587735
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 3333,
                pcmFingerprint: 1048094948
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 4167,
                pcmFingerprint: 3259444817
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 5000,
                pcmFingerprint: 1020824782
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 5833,
                pcmFingerprint: 206011615
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 6667,
                pcmFingerprint: 820943353
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 7500,
                pcmFingerprint: 2290650377
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 8333,
                pcmFingerprint: 2962362097
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 9167,
                pcmFingerprint: 1124218006
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 10000,
                pcmFingerprint: 4060852944
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 10833,
                pcmFingerprint: 3776423261
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 11667,
                pcmFingerprint: 1154875152
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 12500,
                pcmFingerprint: 3981258910
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 13333,
                pcmFingerprint: 1404611597
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 14167,
                pcmFingerprint: 3636039242
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 15000,
                pcmFingerprint: 1204896208
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 15833,
                pcmFingerprint: 2588186509
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 16667,
                pcmFingerprint: 388555465
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 17500,
                pcmFingerprint: 2117601718
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 18333,
                pcmFingerprint: 2756539659
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 19167,
                pcmFingerprint: 472249663
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 20000,
                pcmFingerprint: 3816122327
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 20833,
                pcmFingerprint: 3246846068
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 21667,
                pcmFingerprint: 3313226296
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 22500,
                pcmFingerprint: 1212946103
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 23333,
                pcmFingerprint: 1899798941
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 24167,
                pcmFingerprint: 3958887745
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 25000,
                pcmFingerprint: 3855101246
            }),
            Object.freeze({
                frameCount: 80,
                mediaTimeMicroseconds: 25833,
                pcmFingerprint: 1170404705
            })
        ]),
        majorSyncRecoveryStartIndex: 1,
        sampleRate: 96000,
        source: 'truehd_51_side_24_96000.truehd',
        sourceSHA256: '0bbfcaa1910a92ef9a1434ec8ba3bc99f8f5e7309bde2305282d4d3c19d5953e'
    }),
    Object.freeze({
        accessUnitsBase64: Object.freeze([
            'ggX/YPhyb7ogB4APt1IAAAAAgx8gPAAAAAAAAAAA7MQgkiHz8eoAAAEQAAAADK1AAAAAAx6CBLOXVy//1gGNIgAhZOY4ieWjh0Ueqi3YWb+8OriymbKKmCFyiHgJKYG+PC7ckSatRvzxZr5ggQzIAAQcY8LlOQSrke2fm0jcaiDv8lEAAQ/jYdtjUXNm8aTvZLYyTQzTOy9NHR8rBysOfpYzyp3Ox+O52Np3Mp/Kp2KxuKpfKpnIpeIpXJhNH8mEMgR6jyRx0HceRrHEbxxGYdRmGEaxYRijBFsUI3iSL4oisKguiIKwgicJgmiKJgfhJEUPIjh4h/ECGcWIVhUCxFcMBD2HCGwNoeQzh4IYw4QyB0DIHUMgaQuB0C6GkLgdAqBsDSFwNgYIbgoQ6BUDoEkPgSIdAgh9CQh1CBEEH0SCD+IEIgDyCfHqAAAlUAAAABKtQAAAAAIQYgp6ggS//1sv/9dL//JS//58AA0ABcABoADSbtyr4CWcntZNvpVmRKnz03dG9f7obqbtXc15lSFkiajt9cEz9FcLHFxGKecq3wmmfyWp+hDMJh2+OsEQ/2lMDfHhelRv1b2XNwxN8dYJAEAAIt8eF1nIBlpRdgS/lypggMQAAH3x4XrsbNXEVyqMYfHACQ5AAAffHhe5xmVdpXAcyT8aMJCkAAJOuoePD6Bi27gX9On9/Lp7a04fXcOHdXLd5Z01dVLNnFTTNzRuycT8MmtC7BtLuway7LWcrLBnGmqYyMsGUKSddF0sYn4qVcK6libonVH6plheiVYdomUlqo1RaSROXqgUj8kaYvNAnHJn0hSSFKMyOIyMjyMZicRDkjiIYgbQDcTSAUiZQDUDJ0SiXRDEDBkRgWRChyxcRgVQiBypcROUPh85QsHjkjofMTLh4xE2HTES4cKQMBwxEyHCjiwbMPMBwpAuGiDSocKOMhgo8mHBxZcMlHFA0MNLhwwoqGBhxQNlEFgyOPJhwYOUDJRpUOiiCgXHGFBAcSVDIwooHhhJQOjCSocGEkhAYSXDowkiICCDAgOJJB4QSXFBhBMPCiSwuKILCAggoLjCjAmIIKDAwkyLhhJQbHEmRcKJLDowguNBxJkeGFlx4MINDwowwUEEHB8OMMFhBJ0mHFmjAgw4YEFHDIYceOCCjxsMOPHxBh8+GGoIQhBDBDjT8cMRSRBRp+UGIJpAhFBMDEFEwQgjnByaigGJJKghJXRDlklgORW1QxhNbEJLrIYwqvByyy8HLLb4ppfjCl1+MY0wzBDLLQOdY6AhhnrGQMtgc033BkLPgMec8Ap9r2HRO+YRA38DpHfcMjdexUj34Imd/BUkBiGUvv46aCyDKXzQdVEaB1MFwOtiOAyqI5gAOkc=',
            'EYcAAGBsYYOVAIQRjIXQYIXQaIXAaIVQeEJoQQiBIQjBIIRwoCD+Fgg6hgQdg0EH0LEJIVAkhRCyEQMEKgUIbAghwQfQ8ITAwQwhcDQhcDhC4HEMCGkPgWIgQuCQhdEhDIKCGQUQwIshsFiHCLIcRZDxGEOI0RNFgisLBGkRB4iYOEWRxGBHUcI0jhGkijgJGICOhQR8IEokhJpgR8OCRjQJGPBJx4JVPEwmSATKeE6QTRgwTxuGjpOlhrSB3QHTdsHdYP6g/NHpw/OCzsBcti6cLk8ti1Go2LdbC5XIg/qVAIRQHgPCQq+O8DLIjsrKWoB1kR4M1nKYy6MoCt56sOxlKIzecsDNJqoM5oLZGtBXFeUFwraksiv6a8VxTWxoFReK8qrw8CskCQK6QLAsJIeJXXzQLiWGj1l+EK+lh5FhJGiXkuaVdShZFxKmmYEueRdSxZ2FKwl300ShiSUZuFOGo40lGhjTRaORKyqY0wajmS0q+RMHqZ0tCtmTE7GZKmr6UtW3mS0LGtLTu5UpC5tSlbedKnwbEjW9pS0b2teri1pWd/UuUxbUnTJqXp4di7XNsXaZNa7XNvW7aNSzTPvWr59itTVtWcadinXTvV8bdajbRwVM8NShbRvUb8NbzOzaoW3bm++Op9fbwa65aHmN+9jrlqc537f2+uprnjt966aGW+e31vpn9767PW+mnp3ro8a66uPe2fp3vp3c65+Pe+fVztm2/8Z8/O+PT7xoy/74MvvGfEzzhv+7YsH/mO43pfud/Y67+d63z7hpK9rlfnm/SV8XJ/fN6gp3szf+b0t3ixLf4tR2ebEdTvXiN8V4b+9aEp4rH29qh5bxUPO7UTSnikbU60TCnegXV6zir+04qtznkFO0oqr0mji3KUSV6yRpXjIH1uccZV5SBxflEGFeMYYX4QxdbjCFkm+GKK7n4ql4QRFTW+FE+98IK6nokl3PBBfS7Dy+x0H0uh0H1tbYNpczgQX1tgumytBFfQ1DCTG1DybQxDC2FkHU+VgGl8LEMomRaG4AMQU=',
            '4YYAoGBpYYKBCCA4ZOkAydIGXZAyrMMgzbIGdJIzbMM4yrQGXZ5nGbZ5nycaNnGhZ5oyiZ8p2gadomjqYaepGraI1dTGpaspSxKMtWiNn0w2HWDW1c1tYtU2vVG1q9sGz642/WG7qsuaybOtmv7pr65bUueyN12DdtvWjc9q3TbdwbntS97dva3b2ty77tu67rtu+9bewWz8VsbBbuua9b3ubBbWv67rmv+3cGt+/La35aXBbfva77tuO7rvu+7brua77nu627uu+5rjuW4tyXE25bW5rbtQUmstfYhpPhUhlfAxDie6oC6S+sDyW2qCye2oDy91UF09ZIH011UF0tZIH0thOGk1ZGHk1VKHEtVEHk1JEH01REHU1BCIpqSAPJZyATT0D4glmnxREmnRNJMPCiJKNiySWeFE8g2MJpJsZTxjYwmimBtLGODiJCLji8YyQRYBgeSQjBFNAMEk70uTSQCxRO7LF13pgwndkzCV0YOpW5IykdGD6I2JnlmpaCitSkJZmUiJ2hWIkXlJC7MrITryctZeVmp1xOcutKzkiwnTTKitJZYVrpVBKmuoMXEigjYSJTNxdOQvJEhq+slI40iA1hXTEsyx0xnWSFdCQ6Y1KoC2tIeM7nnS25IdM8lDZriucL91TB3mocL+1i5zwoZNfFyxz4wucYJS57/8qcZJSp9n4odapCiFs0kdcqEkTh5I+8cQRPFCKN6wghfuHplB5BGpNHJlJxBIqsGqFRo1OrtGqVdg1SssGqllopWt/HrVxgdWtfHLkiwStW+jGCUaJXLnBbNKMFMF/ololeiWSR+KbJTYdolPi26U4IcJXglwlfCXKW0HeJXop0l+B3iV2JepnQl8leCHyZyJgJTYiCmsiYSV0IhpjQqGl8CYiX0JkJa4qIl9CJSVsMipjYeck6jYqW2IoJSYyQldi6KSkMlJPYukkpjZqRyMppKQygu3H1UlQXRW6kK6/QdSWqDrS7UjTW5ELaxUhWWpk7itMfYWKFLanIjbVaFrilEndUZF7qjAAPfi',
            '8YYBQGBnYYKBASA0eT1XU9xzfcc3y/l7z1HV7x3W9czze8c3rPVbxvu773vO97zrW865s+u7Nnu0aVrecZ7q2Pathuk5TjmkX5lGO4PluE4Xhd84bc9/Xzdd13Tbts25ZdlWZXNe1TXdW1TVlNVZNdly5ZMvURRs1z1PstzXLcuS1HkuSTF0tQ3LkFSa/MmvVFkNvZFj0w87UWN3BrdP63T+s3BjGP6vkFLc9a2uUvrdr41THL0vrFr6tTHKWti1qataeq2piuo4tp9r8dSvIWnqGJRlRIEIoDwHiJIngXZGLq+crhWqGMK6YvgVpmci2czgU4G8ytE3hUzHc6lA3ifwPaHxzuJ6dDqdmO5HR0elsY/ocGS5mRkWxqZHl+Mm3MSJc3p0+7sZRn6On28DqtOpVO7cqvVeOt26FV6rCMN2BFuuodjsqHYbqSMdcorTdMRnshFa7YiNd0AjfYdI43HRXGsyO63GxHOwoR9tMh3m0iO+2lBH+sgJA2j4z/WOiRNg6LB1jIkXWNCxNQqLG2DAePnExpO0TDSMwkNL1iIWTnDw03SIB5ucNiTM4cD0s4bEmZgyGq5gwNNyBkLXzBQWjlC4etiCIapkCwtnGEg1TAEA9zEExK+AHQtzCExrV0HQlzAD4164DwS3eBwTFcB8PctgyGxXAfEwWAYD4rYOBsVYGhMdkGw2SsDQuauDYbLTBkTRWBoNlog2JqqgwJnnA6G1VAZE1TgbE1TwaD7Z4OB9MsGReE8Hg2mQDI3KaDwXXHB0blJB0NtkA6NziA+G2yQfG7QQgH2xQfF7wwmH3QQgP2hBYPyehAbpCDA3V0Ew/OAGR+7sMCcnQYG8vA4Lzahkbw8ERezMMi9nQoTwzDgndsKD92IkP4aig3deLE8tBgbwtFx+7EcH8rBkvleQH8qxwnhaSJ5UEC+VpUvhOUH9Ki5+6cyL6TGI+FBwbwhPn9KDxuqCEvpLGfuhlN3Rym8IKD9kNMO56wvdBXLsdxL4O3S5ntD+DWkOh7WXQz0bqc2n0M/wAB9w',
            'gYcB4GBqYYOBCGAzIMiyDIMgx7IOd57HqP81SGmLN05I3jFm6Ws7SkjeLWZpCjmI8xROlJFcQ5bkcSoph2KYdyvGUVwyycHTHsdMbiHFYdx+GWPwyhvGYZQvDLEwZMXBVjeIwzh8OsLhlCcIsTRFCcMoLhXDYVg3EYPxVB8IoPhXCYTw2FYLxFCcGoXg3EYTg1C6CsewUxrDSFwJQ3huJ4ricK4uiLHwJZFhrH4Rh3E0hYmEOJw7jcOwvFOH5XCOVwjl6M5PEsOxfDOXxHk+X5DFaUxXlsXpTGREmIEIoDwHhJHmb0n6GeNeBrcboX6V4muZ+BbtTkZ6z3l/kuBfxXcW/x3mPd9pNjDaXYY2lGctZZrbaUa21FG89Zd1fSRdU0GHV9BF/XOXeY0ElGuQsoZzFFOuQmqZxlVO2Mqr5wlVfGImtXwFFfd4suWwlFrlouu4wE13dkuu3ulEh60XXrVyyS9bLJDNQuku2i6T3SMJHdgslt0DST9WLpXc4ylu1TST5MNJftE0lvTTiW7NNJb008mPSTiW/MPJfsc6mGyj6W3FQJh8c6luRESXfFQJfsFElHRESZ+/RJN0FKl/vUaUe/TJb71Mk3u0yUa7UpNzlOknOFSRe5VJJzZSvPbLki9qqXntWC85ksXFmbFdavWrKrFouqMF6q9Y1W11zNUcsaLCytspKqmymqqcKS6hwoKKHD9dQ8fLJHDxRNAdpUbl09FBcpkb1s5DBap0MFqofgsEqCIxVOwv6Q/H+rm4nxc9I8pDMfwkNx/CQzM5pDMnqkMTOCUxL4rlp+5MWm6ly0/anKUMyQtR0JSVHKmJ08SQnTyJyVS8uQrYEUlVtrD7FxORr2Eo21YSEa9REGW6qxC3QRRdugkH3Z6Ybdmphd6SlGXpicZgipRd6QnF4oaUXhiJhWOCmF4jyYTkPpheM4mEZTaYVkMJw+Y0kGZiiKGzF1hegiih85VIJ0DycRpJJROgbRBGkikE6RhMH1DyYVrF0wfSNJRewWRA+oYWE6xRFE7BZcTsEYAAMQ8=',
            'YX0CgGBhYXmBCCAyk85EloKQp7MSYzVNZymKgpvPRP5qoqaqLOaPQRPyaT2nz0q85VcgirUkVek10o9hKWXVRrdZrKv11XrCWOyrGZSzWUWi2hZraWq6rPdzbd7beriXq8r1dcDe0KXZIrmlV6xuHxOOwuXReXxebxejROeSOazua0adzydarNqfVqPZZ/bqNZafbavba/ba/fLFuNy3G53G94W74m94TLYbLYTL5y/a2+77C67O6bSa/I8bK8XO8XK9XO8zXbzquoEIoDwHgQmE7EZKJ1oCUTtQkozYfphG1BSDdh+mE7j1cZtP04rYdrjtyAlE7DlKP2n6QXsOEg7cfJB204SDth6uO2nCQhsPFhuw4Skth4sN1nKQpsO1h+s5XJazpYprO0hDScqF9h2kI6TpQvqPUhPQdKGNR6sWznipfSeqmcx+sYznzzWY+XNZ0F5zIgKG8qEocyoSh3GhqHciG5BiRlT+NDaivpKp/CjMR30pVFfSfpL6YqmupbEtxPcmupjVNxSamsp7VlpVaosqP1llYerqqn1llaYvqLLF1Za8wprrmFJe4yqL7WU9j60pMDGk5m21oMzHE1m21mtf3c5q64kNvHc5v68it/Hkxy2/iunXsh13Biu+38R65EiPOYMF/7DhPl48KC5DfQGJMGE3Gdw2Zb+HvHdRO5r2JtJbx+57yMtLbSGaLmSxOaydaTWU1SazNKTKVxTZztazKavTYT9bDGetXXUNa6+irbWUlrCyklbW1FriinlbV1Vb6iqleU11cCerhgTWdsCeshiR21MSawjjRWs8yO3hjRW086K5PlQW886G7PpPXc9CC8NoO3ktZ+/PpOXx9pzAlsOYBNZrBnwO4Y+oxhS5HMMfaXw48DWKTeYwz8TOQXgXwjci+SXkYxR+RbGP0LZA/Ivil6lsgvMvjDdiWMboZyRuxDFL1MZA3cnkF6FsQTyTyjdCmEH9Fso/UlghvBbKL4J4InYrjj+SeEN4K4QvcniwAKAc',
            'AYcDIGBsYYOBCCA5ruua+r2zK1sWya/tDY1mWpZtmWpa1oNp2jblq25bts27bly2zclu3JblyW7dNyXNdG5b0t28NvXg3fcBv+0HDrA49XDj1g4TamG2g4PbA4XaBwW3MJtS/Lpu28bg3rbHBbZvDdlyXjaOA2ZfNwbuug3NcG7LRvDbtwG3bg25cG2bkshuywN61zdGxbg2BuGubZsG0Ni2Q2pYGya42rVBtaqBtaoG1KY2hqyuNY1TXNMa8qDVNQahqmmNOVDSDTlIadoA1bOGtZgapmyoM0aUnhnQU9gP7LYAnQnhD/S2CH5lL4f6WwROpW8F9FsATyUuRu5i+E9FLcXwZvBPBW3E9F7gbqYtQvsvak6mbQJ5L2I/Y1ZBfBmvG7G68N3MVovU9Vh/BirF6H6gL3NU43Q/Thep6jF6naUPzQzwfodoxeaKbCcz8+NxRy4TohnBtyWVB+iGWG2qJQLxRSQm5TIB9qWPE4Ko0NsTRQm1ZFB9ieHE1r4UNrTwofWxgg+hXACal7+GzsH0XOueguZm+D5l7qEzNXgbIxcg2Nu5CZGrkHwNW0TE7bhMDVqFvvGwNgcsw9x20Brz1kHuO2QNZgsAtx4xCWYa6LYfrwteEtC14q2JVgq4taQsjUoakJVlKw8+MpCVJSiNOkKQ9GYliTJSiWhOShJEtLJOoJokiaimk0UwPIooho1FIFkVUMkOkiki1UIeDUQyRLCAWBVQh39k+NBsoI7uwemf2j8d1bPTO7h6Z1dPSObp3BxePCN753BtgOjNMB4drgOjMsZydngO4McpydfgOzsc5zBXiOYMMx5BVlOILMx7JVmOIKdB7JTnO4qdB1JLoPop9J1RHpQIJdZ1RFpQZo9h9FDpP7oNiEdBqP8H9aHA/tQrnNSJI9uQ7G9aNQ3sRbG9qRUzsSLGtyTYtrSrG96XcnrTbmd6dYpqUMFeCfcrpVMEeKnktoU7j+KvkroWMkN6vgjrXckda1sfuXsD9LBwjuYMDNDH0huYsjNDPwftZdi87XwftZ4Adxk=',
            'cYEDwGBiYX2BCCA1xBs+AG62DhKxvlI4GkbhrtYNuoBslZnGw0GoaJUMxqkwNNmGgZbQGOzhis4YrKMkjMZjMZikRgGKQjBIS+MFeDDXAw1wL1dLwuV4LUfjQXO4C1Go0LVZC3VxaLFYFirBZihaiQtZMK1WKcWigqZQpxIpxOJCpkBTyAU+gFHoBRp8QE/HidjxOx5Nh9MhpOxYTuWTYXDMWJmJJmKhcJpdJJXKCRioRCcSR6TSIPSKPR4RRaVA8VBIRhCRxYNRoLE8gQigPAeEmxOahwbql8FaKHRuel0Voo8FZq/heen0Vlt9E5q/xWW/wRjuNF5cHRGHD8VlxtD3snROXQ0TdzfE49rRFzQwVh4sDXNjhd/mwNZ5NF3ubw9jx8Vc7KiKvv4q77WEU/jRVpi8VS+vE2WbxVBm4XWaqiaLVouk5XF0HDhU92qNnO1BM588fMeri5ai8dMUFhcpVWISFFQbJWFx8dSUHxlxKQiqjx8VdSkYSuoQhryQnBWlyUJfWJvVxIUgpFco8X1ij5IpSrpJLl3qRWLOEmnMukk8s3SqMabpR5dslkQ41SqxpolUxxol1jbJKoh9kl1jq9LJj7JLpEC1MJT69LJUSxLpUKxMJkaxLJUqhMpUqxKJkqdMpkypKLqUqWRU6hLLqkqVTqkqVSq0iUTLUiVSq0KRTL0qVTLzyQTMEaTSsD6+mZH0inZIF5I0OpBFanlxI1OLydueWUjg0uIrg8srOi6yjuD6so+KqyO7PKyz8opp3x1TTQSqgkfmlNNDLu00EuoJYxd2mhFXSWQXcpYhVunklmy8ko2RJBZgkmlGieQV+rUCrFPKJ+0tIt9STCXdNUL+15xHknrF/C9AnwSVivJNVKblqpTentFNStQrrSXSudJXKaElwtjWtk8iW4XwK3imBNdK3X3y9xNhK2lb5iutiLWFsJiktkL118ZmaplMVFspiUvmNT36DMhfMalqaTcVTSakLajsB2s1HW1oDrthqCprQnVN5w4/YhMwn2Y=',
            'YXgEYGBhYXRhoNxSNxaNRKNg6RAmMIiRAiqKQ2PQaPwSMw4JhOKQ0iBERCCMkIisOh8SBsWBsOicTiUTiQRRILw+JRWFR2FhsIxYIolG4jEozEwqiwZIpGRFI6RaMyOJiWJilEpCR8QxsUo2KY3K5DIxTJZDMY/MUnFKXyWYy8UibCkTcUk7GKZjUms5mNBnc5J9PRQxyKGPRRqCUWe0lS6KKVTQo5VFHKpSaypNdU1XaiK2WRW6yV1XVhrpY66LXYSwrLaSz25rAz958y7efMP3JCj+R4u7enIu4oCruaUffxRkGclA8/okHP8VA8/soGO8lA2/spF/9FYyzqqFP91ouzosE/dlwqzwvE/dV4j7ywEf9WIl7wzDvvDEQ72ah3vloHu92wc75bh7nlsGeeHIf54chjvl4HdeXQY74eBzHh+Gf+Hgbt5gBn/mAG7d4Qa54gBrPmGGsd4ga34ihu/iOGddowdx6kBjPSSH7+pQZx0kh6/iYHL9Zoet2mB2/egH785oer4pCNuE8Qt5qCdd9EP171RanCmJV62BWe+mL26WhWW2sM16WRmey2NT5Vxumy+Ox4WB2uy+Qhsuj1N18nHVeIx24C0tF8pHXjMQ0YC89GM0XPjNzzYjxc2Y9LNiPlxZ4Ms+SKTBnhxyZY5b+mSfFklHv7JhLuSafDsnGs56Jb+qma1rplt6axK+2yW3orlqbr49rVZNR2YxbWu8ehuyC1NWQtHdlGoatBKO7UPN2ax5+zcNM3biTdfISXu4llbOoePt5llbvIeLr7jx9/wWLq9jRN/8WFp/Cw9zMSBqYjQdrcR9rZiv9TkR7tcCvNLsO71ux3Ol6Gdano7fSohXGlQI20KQRnpVB22ZVCsdSqK0yLIjDQqBmOZeGYY1UKt0L4q/AshledICq8C4GWZEiKpwLoVRhSQynAkgiXAkB1F9Kg6K8kBk15LhUN1JCpLaVDoLaVDIraVEP2ksHQWEoHPWkyGPVErAFaU=',
            'AYkFAGBxYYWBCGIapZV4/f4NjYrtlV1uyq9j6/j7PnLLxuns3Osru3VzdK33H3/G7/G7/1bxle9YX3WFf5hXma5hbOsqa5h3GZdv2mbZ32GfdrX0mrUJt2+k5j6nWUe8tRqhb3qvfdSyn1ClWqklOq1KvWKUcvW/y9Sj0h1Tr+VrW8tUuZb61a/VqS/khS30l1zJDJDL/SFJHpLL3SOS3Xul+kKSeS1JHpjJDJbpfpDprpDJzL1J/pLpvpTpnpjpbJjpvpTp7pPoh0h0R6StP1LSTtS1p/Jak/0pkQyWycya6byapO9NgH66CHbSYCnKKWFNWUwFOUEsKYqpgMbopYQtTS4czOS4crSSoxiamQhKekxzEtMBCU5KEKSUqEKS0sORkJEMSkpcUlGSAYfISoxKGkAw6OkhiEBICD4qQEHP10YdCXw456uDDYC2ILerYo94tDCXawIOeLI4lyqhxrlWKKcqoYU0UjC3SoGEsHphbhSEEsXhBTV6OIXOhRTN4QStaiiGTkopU0FDsWphSlgMHWMyiFP0gpX/MHU+hhSf3AQo7jiU3g4hL0HFJOhxKbiQSh4QEJd5BiDVAMj2lGns8BCLQcYeymEn8kBh/CcWcwRFn7phhq7MWetlHGbEhZyvAcaqxHGqkxpqeceXp1Hm5sB5WZQgblxIlJMiRmPUgVkRJloViReJEoVgWKFYMyZY5QwVP1KFDFDBY5YsULWMFC1TBQtY0UJXNFSdTRIjk8XH6mCI/lCWHamyg3pCTHKniwxtEUGbHygxtIVFcIiYthGYFNpSQphKZEtpiQnlOaENKSIjxQcENqSQf0sOB/qsoHsrjYd+sLhzTEyHvrzIZ0wMh/7M0GOMjQd80OBnrU2HPtjoa81OBnrk8GmNjoc88QBhjo6HPOkQZa+QBtjtAGmQUgca+QBn8FMHlISENegpg86KkDjIigOvjJg62MoEHyFQdbJUCSkhWHmzFgmpKWCLpy0SUmLRVSeuE3zmIq+kvGFaLIWUoshtSszGFqLUbfYZji9RuPPsNx2AAKcx',
            'EY4FoGByYYqBCCIaKcqYlPRTVTkpiKe01FNacgpuTECn1LQKIyUgURkxBTmmJT0pTRCFKaJRSGiUUlp6KW01FMVMSmKmIpSpzSUU5pCU9FIaaikqltLQpLTUpCpapaV6UtpKKU0lUlKS0hKS0hCkZKQVsSUFe16pCr1XquSv65Fd1yKzL0KrpCKjpKVKruqSualKvK0VPVqqVSqvvpV5Qio6lX2pbzUK61Lc6hLeUpaqhFrPK42u6lquJazaWc22VazCWayixfNr8Vn9/l9fI9vl5erzbffh/1n24TqZTi6dtl22fV41tV4gaRIvZbklK7gdWtuy61twPLW3xtW67Ipbj44/A/Lprj42rjgnUl+CcXyQoSS/EPrZocRJhjQ188WQlxx4y2iTLT5ZEpXTJmp88yetslz0+eZTX2zqaXVOqpdlCsk2z7aXbTsJd1C8l21ryXhQwJeFfEm3VcaTnVyp99jOl5V9KXla1J+Vjcv0t7UXla4rdbvBE53Oqbte6JOd7ui97/lfrf8InfD+SdsPtE74WCXtkYpvF9mn7aGSTxfbonjU1SdsDlP41OU3nE7T+NbxN3yPk3vUoJuuZ+l+6lNNz0qab7oU0vTWrJ/elWX76lhF87FpbzoWEXxuXlfGpaRfG1eW86l5P32LqXxtSKXvrSCbxuSC/fak03bYkUvfall+u1IJ++xLK9tqUTc9qVS99iWW570qm66kuty4JVL20pdfhvS6TrqS6/Dcl0nLWll+WtLr7tqYW56Usk17Usry0JdLr2pZXdoTC+7WlFdmpLL69CVU16ksk050k7VpS6XVlSDc2lKpNWRIuzZ0itlypB+fKkFcWNefkxrymTGvvwYllTFhXlMOBYbfxLSmC6sOuYlh+C2qut4VZ1uyptuXlFSvZUu2rr5StWUfWLrl1ao/9Utt3VKbrtGu3fUqtuz6jRtGky9NpMPUKLJkuf75OoMGSZ3fk2f9/GldOS53j0WRy3ImdfxI23MSVx9Fja9v4+zcWJp68jaMQ4OTzqHou/gXeu4ebD17Z24gYcvHtnDR7Zh81A==',
            '8X8GQGBgYXuBCCA3asLZ79aS8WkuRxt1ptxltVhsxhWav2Mxl+vl+rWOnV+nVsl16l1smU2lFOlEmiUuhUqhUefEefD+gTufDehDabziZjqXT6XTaZi4biYZjIRjYRi6UScUSeSSsOS+OJPHEnDQmjQqCUqiwijQakEWjEajQWjwWCkWC0UiUWCwOjwKDUQROIETigicQIeECIxAQ+IIcFoYiUQhEaAkWBwMInEBE4YRcEEaAkeghGoYiQURMGCNggjwMRoAg/KBCKA8B4EbeOnirJ669ctnWrF655bM2/DB24WZsm3K5u11Ys2rC1o03WsWWi5izZVMWOaxew3ULmKqlcuVULV6qVYt1UK1qaRUsVSqViiRUqSQJVSyZWpnOIlKyNSnwPI1GiBIlxOJU+Z9CkyNJEuB1AkyNIkeJg+kxOIEWBU8iRNnkYxU6gRLnkWBY2gGKnUGJQ0gGKGz05Q2gGJGD05M2emHlj0pM4eQHlDwciaPDjyp2UcYPSECxwYYWPCDy5yYYUOxxpc5KMKnQwsqdlHFjkYSSOijC52KKJHJhZU9EFFDkooqejCiR0MKLHgwgifDii54KJJHwwosfCiSh8KIJn4wkugiiSKAMIMoQcSSQhxBdEDiCiEKJLpAokohhxBlJFEFEgQUaSQ4gqljCzCWFDmU0cYXTQgY0oDjjCgGDGlMOMNKQos2qhhJpWFGnlcOLMrIYWhWRhppcCjUC8KNPrwcceYg41EwBhx5lFHI2QKQQNAo9K0hSCJpGIJW4KSRtYhJQ5hiSNtEJKXYOUTuYYmpdxSqp4DFVTwIWVv4hZW9Biy2EFMrX0KZYQwphfBhjjCHFMsYgMcZxYh1nFBjjKPGPt48KcaSAqFvKB0DiTFROZcOidSwiFzMipHs4HTO5sVG+nxFL+eESPqQZXCoAyeBTkVw6QOph1Iy2JUiLItQKtjWAy+PUir49kMxl1wzGTZDMpdmK0m2Q7OZbDNpluM3oW5Gs+3Fd0bwjehcEe1L2AA1aA==',
            'YXwG4GBjYXgRIMETCgi8YEXChHgojQQkkOEiHCSII5IIwkEgRiSRoQEmjglYgCRyQJOJCTCxIJYlUsEqlhKhoSaaCXTAmEyHBMxwE2nBNh4nE8T6gE+ICeUicFOnhSiQoxIUwpVMVCkVSmKhWFIWYiCzkwLGVBYi4rRkVhZLJZLBbFmsguZgF6Mi5HC4LZfjYX64XxdsAXo+YC+YRgkIwmKQDGYzEZBiswYdODF5gySYyGmSGgzSgZpXJQ12k0DXZxslVpDdaRutJvgA/SIK6oXh3li9Ff0L8r2zfjwat+V9XwiRLOAV/XxCR7uEaHXxCRruEWPaxjR72IWTcxTyb+OaVfxDzL+OaXgxzTsONGfhyDT8WLGjiyS0cmPSpjyCUc2NSvjySUc2JW1myi1c2HSxpxz2MuPS1qw4W9GPS5pw4W9OLO9pxJXdWDPDrxKXteBHDpwq4t1/TBpwJ5d99THpvrZd15PLrvb5ttzTPturaNl1bRtta6tl1jTusK69lxjXur77NlpbZurdbdljbbsrNb99bfdpqs8OFTjhoqdceNLnhnps8+FDrlnpNcd89vppoOc9k5nlpm+dtc1vnol99Ncxzvokt888r7zqj+cskhz1qjf9MsZrznindcsTjxlhFO+OIz4ywDvGKF54yPjvGB/94yPjPN94/4xPf/F9zd5vPHvGBwf5tuXvN5xf3ttbPN1vd4stDfFpqd4sM7vFhkf5rszvFZgf2qMbvNZdU6019TzUW3daK2t4prL+05YU60VVXvNVXc56kk7y1N3OaoL9ZSer0kp6nGSmJekhMdwipSXpHSVeMVKX4RERXjDSl+MNBW3QUhJvgIKm9+ipdb4/W4PkJfS9QEu9yfKaXqCn1tzpbW8QkudmdL6nh8lzsTxLocna+RgeJtLc6Xwrz1PnaG6+BcfJsbE3SYlh4lvsDlLhVHSW6vO015Ocpbq47S20x0muqztNYSnSS2pPE1hMdp66Y7SWEp6iVEh6lrpDyABmKA==',
            'gYYHgGBqYYKBCCA5kyeMzTBoaYM+zjNNGzDTMu1JLNWzTTtAaVoGnaUpDT9MNT0w1HVBpOqNPVzUlWV9TDZdMNn1A2nTDZ9Y2bWlm2LYti2DadcNt2A23XG464bvrS7bGuGz7hte2bnty1rttS7rUu65beuW7rVv21b/tG+7g3E3huO/bdv+3LzvG479t/BbTwG2uGWvglt4ZZeK2Nj9e4nYmJbRvLdtz3tb1527edzXfc1z3Xbl13LcW3rmt+57duJty2m3ba27adp29ZdrW3Z1pbVsO17PsQBmbYEIoDwHhImpIRBNVSBxLQQCKJSQB9JPQiCJROiaSYhEUWebFF5aATRJhsVTSDgummHBVNFODSWWZF0SEbG0kkyMp4JgeSRTY6nglR5NBOEEkEmRRHpsovBJkkV0aMLvyhVO5MGUj0mZTty5tK5KH0zUucSOScFMzLQkjYrCSsScZM0LRUrAnJSMSstKwKSl1pOclYFZy6onSTLS1BIrJ1l1JWqmVFLCqYpZSqSlxZIWuJEpS+kTFsKqErhSIy2VZGWyLny+pIiK5lD5rcmOlNbkBvemNluLTprimNmOrTJrokNGvDzRrwsXN+VTBv+8wd9KlDbNQyc/PIn2ihk6zeRPNlSqFu0mfcPIIXahRA6aPSPnkkL5w9K/cSRqTRiVQcQTKzhqVSYOUrDRqZVYMVrLRqhaYMVrLBipc8LXLrRStb4MYJBopYu+Fs0j8StX/CmaS6JZJP4pkkuCWyU+IZJLYtylfhWiW0NdJLwNwmtjnKT4Eepfgtwl9iICW4JeJfQh8ltioCZ0IfpXImImOiX6XsIjpbgqCmMCYyW0KjpawmKl9i5iUqJipjQuckqiY6YyMnJG4qYlqjJqQyLoJWo6ev3Fz0nQbTXsD6KRmMqrtyFJfkOrLdh9ReoPsrMyFRcqRtLFCFdXkStLFSdtTiRsrNS2B/AlZVqF8L2RO4pyMYHcSt59EzhcyLYHhzeNtMthcGOZGkjORqc9jZQM52MEGP+c5o/GQZfUDuj5AK8p',
            'AX8IIGBnYXuBASA1c1xHF7xzW9cTxesdXpHOaRzec83lPFaVres61le0Y7xF+bXi+nZPjmlYVjeU4XjV94zhd+YTftz39bN923fVd3XXN3VNd9L3ZPdtVZTdd03VVG0xP1MzZRdFS5TcdUbJM+xzNscy9FEvxzDstP7Lb1ya9Mev1BkGQU978Pa9buP45b3Ny97Uuc3LftU3jWNYzbWMWzjNsYxi+MavSvM2ljNp6vaerWli+oYtiOrYfquIYnaPI2lh+p2dqVn6fiGHafRvoUZx1nxtyxkebuY7o7wS5+o6HV0ikz8R0mvhBNo3DpNW06vVqGSa9R1enMMp3ZjK9WMdZtxlWa74y/bfMt23BWOq4Zfwrh2emydjwqiNNVQjTfQHa66QrfbMK23TwznZJM42SgzvZHHebo4rvbCGf64ojvafGg6oQr/ccFg6jwkTaaGg6jIkbWaFiaygkbUWFj6igkrSSDR9ZIaXnHw0zUPCzNA8JOzjgebnGhKWccDzsosLSzjQaljFRKeUXD1MYoHq5BMSviFA1XCIiWcgkJZvh8NawiAlm+IBrt8Oi2r4fCXrgbGv3hALcthsXHbDgW7bDomSwGQ+G0HA+OuGQ+SuHA+SwGg2amGRctcOBtNEMi5aoaD6qAbD6KgXE1zQ8H1UguH1TA4LsnBoPsmhwPtlhobbLDobfJDgu+SHhN8kOh+MUPC8JIgH4wQ6NykCYfjADwvOIJi8YAmL0gCQvSALCdHoqL0fio3R0Ni93oqLycjo3p0Mi83Q4N4ajw3VwODeGpIbs2Hxu7ImP4aFBvDIsN3YlB/TA2N2YFieVx0fwuOD+Fp4npWfH7rIZfSk+TwqkE8J4RfKqWXwmkF8ppRvCaaP5STz90k83hHTP4R0S90Ng/lHVh1P2iekFmXQ9dJ5P3adTuEnY9hn1OYy9jueXQ3lh1N6odTeuHIzrn2Nbz8TPCnMxwhzM9ZcDHKfEx3jxL+abi3ifIx8nuK/a7S/6O8sxvsKspbCrOBWJw==',
            '8YoIwGBuYYaBEGAyRbIJlMgkS56RTGplsWkY5aylGKJWWxSRCi3HWY5CyFFLHcpYqi1CLMUIolYzkLGUQsVyUhGIWK46xFEKDUQ4ax1CKFWMoVxEhmESF4aY3CTHcJYzhKGSD4iYrBpCuIoNIRg0hXCUIoNQqwmETD4qYfDSEYVILjJhMKsRQbiLFcJxkg+MkEwyw2FUKoRhliKGYVMWiohsIkOwziqHcViFi8dMfDLJcZyFDOSoVilDsQohRHKTIxSyWIYxZGLWS5jkuY5LmsU5bmqM5izuYs3mqO5qjmNgAB6jW2lm09RNtjWXbz0kndtRd1fQTeU0FH+MxR7TMVUs5CajbMVU74yirjIVVb4CatnIUWcXiqvfEUW93Cqze+VXtXiq5m2WXtXCq7q0WSG7JZIYtFkh6uYSeLBVIfrGEpeoXSbaxlKXol0qyoaSeaBhLtom0rmgaS7JptKcnGk16YdSfphxNelHEr6SeTP5J1K/jn0z+QeSzIaJL/ioEw2GiSrISJLsgoks2EkSzHqVKtgJEq14lSbnqhKtdp0k50oSrnChfc5WJRzZQvvcLUg9orX3tFy8o1Xrr161dUaslt6xetqNGayqqYrCjBosqK2iostZqyihyprrWak9K8Ul1TV8oleP1k7l4ulePVEb1wkTPXKx+A5WSv2i59+1XQw2S5+AyXPxv656F+XOx/iU3E9LHJXlKZi91zkvukLyOaQ1M5JS8zkuXmbUpefuXKTtacxP1LEaOdEMUMy4+nlTFqWNcfVvpylXCkHVLSUpZuphdaylKWbCYVYrJSdqmlF26icfaoJRt6cnGW56UdfkpxV6YlH346YRfjpx2GKkE4IacXjhJReGAnE5ICUViOJhWU2nE5TaUVlMJhGcwmE5CqcVpKpRGUknEaiaYRnHkwnSRSCNA4iCNQ8uJ1DKKH0jqwrWLIofWOLidQmmE6xhOH1Ci4zeKogfQIrCuImiitIisJ3CScXrD6QVuEEoraHkgvWH04neG1h2sRTidwZWG7A+mG7gysM2B1ON3BmALkk=',
            'QfEJYPhyb7ogB4APt1IAAAAAgx8gPAAAAAAAAAAA7MQgkSHf8eoKAAEQAAAAFK1HoAAAA3aCBMABJy//yg/v/QpCIY+57BpGgbOGwJPM5mlhNTfLiBKFv5R2BUJHI66K8nY8z6UwN8eFwtJJFhReoS0t0FwagQABB3x4XQEh3WVd4GLtHMdB6ZAAEJQiY6gyZVhUzOHSHWKsdYyiJi8iIdhkiqHWOoiiuRMjGSI5lkUdx1ywy6YdduM1rH9pF8rNrWVrc73zqznVmpc3Fz9aPyp3Km6rLja2XldMXx8+1jdu7dnft7r3bWdlbW90azjczTd3G6vzzf1CezxqM8SzPJXKm+LRWqGvH1INbqjSdQSRlhJMuS8SmsaUa+SBpMmEkyUNLkoksTDSklNONKaIJJEUSUaY0UaQaKScaYaKSYSKaJAA5Vjx6goAJVAAAAAVrVHAAAACEGILHoIEwAEpL//KzAASsv/8qGjF5Rrsmss8rcUOpoyWfxOuI5R+ogdRkSeigQjyYCxHUrHuYFGfLkUGCbp2NshKZlHHn4FRscXykVNsOM+mLY5YoMQrTDcU58YeQxBPJYao4esCUwN8eFyRIz1jjeQi45zfwc2QAAj0x4ZCMm5LLX3cIAAgb48LtuPTrZW6QmDTk7hB0gAARvjwvnoxeu07gWZPOLuEoiAAA6W8oYl+cPSrJHpPmD0vySC+ySCW8keusYkkeQPXeKVX+KOXPDLLfFJLu/LLLFJrlvDCnwii3vDSp3pZV3ppU7gyp7s2o7Y4pTcGnhtECpNqbcNihfWzPuOuQv1ejaTXJHjVI2k1SZw1KhpNKmYNQrcTQKPTTrGkzi780Sz1M6w+5th9zjPxZZh7zLbtMmz7pZx0sg265Bz0sg73cU74cc93cO+2TEwN6Gg6LBwdnCxclfoergpGW9Rc1fZeDeo+TdpuKvMq7cqGLdp1it1C9uNGzbaVyttWvaalitVelsteuZ7NSLFZobJbo2C7Qq/anSv4ZWtXZ1XMUirGGTWMMiVTLG1fFI1LPAlRxx6jphafmgVN0wKmaztLzwJStx2kaTEo+6DRtZKUXdAqJuHtB3nqibxynvA1ofAcp3yKVA3j2d9B6nnAjO+o1TrgPU46jc55DFN+Y9E36CY25DVNuwtTTiLSa9xeZchCTXqLzHmHpM+olmXIRmPUPRM+Qey/mHsy5hyTHmHMw5BrMeYckv5BjMuIapfwC2Zcg5S7gEsz3hyS7gD403BqJbuCc22hSluwKSbbAhl+sLZprB6mmgJZlqB6TTMEs10hCmuUHZrmClN8oNU1xBOdZQYzW9DLXA==',
            'QXQKAGByYXCVAICwGTe3JN7cFYrwXgrFuKMW4pxVizJOS8V5IyXkrJWKs05KyVknJeSc0ZLyPm3M2LNUYq1TirVGKtU4o2VgjRWaMk7JwPqvM2SdE6HxTui9PCMEaoyTobNeRc1aGyTobNGiMUanxRqfJOZc1ZE1XgTNWZsUaowPmfJGZ8TaJvNqe8+Z80Xl1TcXRF5sz4IxLki42iLjZHvNkm8mCsB3pxLafNFZNE2FyRaW9N5LU4lsRea49xbkXEsVeOxVw7FWktRWW49RrT2FqPaes1R7T0GsRSas1J6zUHtLMmwlCqYASQqVAIDxAgRAcyp5jKM5vGGd4Cme2y6J5fLR9aKKfWjCoNooqBWKyFZLIolQrodUq0ekVVEpldLoFWizyqp04pJE4qioSismSyiVGSWk+QTVVjF0qMUnK8Uu1SCUVchlWqvijX4BVVl4W2J4Ta28MKyuCWwOjDZmpVsrcq2hoY2piUbW0MtsXFdvYl24rS+4rTDc1hWd1RtLsqKC8pzaL2oLb4lMz6lNcAiLrAJThhEBdMGhN0SfNuGQGeMNnOLQGnHmTlGnDbkzZzkS53lTRzli57lzB2mSp7myx9zhQ+Z8qeTPk0JoyZ50JNG6cgfqQij6gihqkgidSPSVcQROsGpTYEUfXC0y2g9INkOULajUdbDVXbjklbjFS3Y5Qbcapd+NVV0OUu/GLLAGqnfj1XhDFtgj1jxBq7wxy0cceuXDHL7LHsDhj17zSDE4hBj55Bl4xJic8i1eUTY2aSbWaTZ+aVbeeTb+aXa2gVc+eXbPQLuRzjTl6JdxaB17aBl16R52c829tM+9ecfeHUPv/OQvrSRwLQRQF0EkAOglhLop4A56aJ56uD6CeNZq6EdBVI8xdCs5fKs1dC8tlMOayiPKZy7LbR/JazbJcyfHbTPIdy7HdzTivJrxXs0cR/QeFAnHCh0PAg0fCj0DeQ6TwJVGuotOvplNbiPAANJj',
            '8WsKoGBqYWeBCGEQG0vgmi+DYL4TAfx/BfH4H8Xgfh/B7E0LInA8iYD0XgPh7BcH0HoXRZC6HgWwex4C4HcfAWDwC2VQfCqCyeAVzwDuWAqiwKodxWFUPApCwKYriiLAoDuHEqB0HMUx0DiOg5DkOQojmUBROIUDgHE4hmOYZYkGU4jMMxxGQoDHOAyGcY5nIcZyGM4hoOQpHMUZpFGaBCNIoiSOQpkMaBxiSQxYFGPQcZZCmUw0imNIkCmJIpiSJAshjGoLI5hLGgLQphrEMNYeA9B4D4GITgvZN1MbmdU7mXXrSjSdzNsDYU6jtaFjsKlg2NSu6ytaq+vYqqxZdTYtmpuWlp7VsaW7bdLeu1DfudDfu0/iu87gvU5lwc1humY0YnLYrtL6cXJZcHJ6sFIZsbjtmHjtGKit2LitORYbfkGH2Ykwm7MMDvxuC35t+34595Z29bspe+mdu+/K3bppnXhl3Lpq3Llmm/npVu66Zr4Z9r76m0cdGz9tWz8tOxdtLZOWtr/TTMPbYq3x0a7326zx0qt9dkq89arPHY1HprlXjtSo8tMncd2pcdSpPDZp/HbpO7UqVv3SRw2Kkbdci7t6UXbpKFt3qiatLQNm9UDRrkHXsRPM20oGnWzrLtSe59sc4tanebbm+DUp3l2szu61O8e3M7utm93Wk0v7IzsakmtzXmNjWzaxrUwr6WZ1djMa2hmVHYy+pnZnP1qX0s+ZzdbL52dmM3SzGVnUvk6YylZUS+LpjGPmUwh5kmEPQzODki6FmQmr7KS9/lSau8jMHmRTRzlZm3wqaOsrNmeJmbfEpuyxs1ZYGcMcTN2GBTlfhzlbfU7WYEnSy+z1TeU6VXVQE11nqa8qAntJQkV/P0tho6C8lARWdIQWkoh21JKCwikm7OlH7CpZiulNPVmnFbCp52mlRKWJTN00VQnUaoYqNWKUmsk6qVcrQl4jACyu',
            'EWsLQGBrYWcQlhKFoHoWgli0DUPYLQ1g1C2DyLoPAnA8C6D0JgPYuBKDaFsPoSQ/hoC+GsLgfAmB9C0G8LQdgsh/C4H0LwlhGEsN4aw/h9DYHYLYzg1DsD6N4XRPD8H8P4nB+EYPgihND+J4rB+GcThHF4VQfh2E8VhXF4VQ3CqG4dYvDKG4dxXIw7DrH4dMmjpE8qx/IsjFcizMOszlcyyqM5UoMRcVleCRlHc6UXMuC4qMuijJSVFKDzTiqKc3kim8kU1SXROL2RyayFH7oc/ujk9kdVVTslWAAEP6UUVkpSbGQmqtk6bZR8tWElRSzD5jZSM1tQ2alnIym2i5ythGRuAyarcPjN0GS1cxsdu46O3YXJV6IREvIyPvwyIi9jo3BjISv46I4UbBWDGxHEjn6w4+FxQx+sYRfuOGwOOIvEyI6A5Mk65Mg+TMkXSyhJ7zxFumXJvefJtkzhR10ZRs58s4dMVbpoi7eqi7RaQy2WsMNOpONOtMMk1h9l15tktieYuxPsXZn162qBi7dGsdqhZLdJVTt0rHvEqlbpUv79KpW8WLPAUqVwFqvwVifxFyt4LBOuOwUWGyTvIZp3jNE1kN0y5LZL5LdJ5jpI8h2ls52h8l8lXQfIfLfojnwUac6Gf86Gjs+OeXQhoLOmIF0Ix70ZiCz5R30Z516Mw/aNE16M8/59MxadJA86qX9Ooes+wZ9GuctGwZXPtmjoWjXoXTPn3DPoYDNmXjL0cRiyr5h6GUycjAWehnM2NjKvP0l/Fxlzm6yy4uYucjYVXG0GTi7CS4uwyOHsKLh7Sw4O8uuDrJjf8zC4GolXvUub3aVW65FBvOJZNtyKDccyrt+JTs+ZatuhTr+RWs+pXruhTr+ZU1fUq6zmU6noX6foSqjmY6XqSqPoYqLkU6DsXM/wKc91L01yK03xLcv1LUvwL0rzKclvNOT5Exj+Blx3CAADRb',
            'UXwL4GB8YXiBAaEVGKKUYotTee9dp81XovTmm9O6LVbnvXya9nJsW7m1XqndPKdU8p5Vujteqe1ep1Wyjdfqf1dq9V2n9XqmVdpbX2ltnp21sqbT+x1X6XVtpbW2p9TanVOrfQ+1s6lylDrFKn0qWvoVsfSrWpWpSrarQpYtStYpQktVnWuWoWrVrSVK1r2L0r3Lzr2L1pKV7Uk6S9JKkwSzL2p6lKkWtWtEqWrT1Ja0tSaxNQkuT0JLE9SWpPYlpT2JaE9yaZPaloRLE1SetLSi1pqU1iJQmsTzprUWdLai0paEa1JOjWJaEaxJSjVJa0ahe1CTLWoSdJYjQAANRBbjt5cYjeYcXuMGG3mOG2GuE2Fxgthvf9ZdwGk2L5qNN80Gp60Gt2zG530G9zxG26ZzguOE427Gd27CbFswHm03jhacB/Z7R7Zbx8slk82G2imGue12ui1+uflimj16wh1acilesjKvMRanTS6pKRShOTSjMSydIStOlptLiJilyVDSYabSIiqRoadUZ+rFEhJ1Q3a0ocBRn7lbIjxXnbhZobhaThutVBaLhN2rFJ+yWhNmbFTtgwjZexZ0tZxqvYKbKGwm65ikzSthNVbNTRK4jJMzzVK5jBG2zNG4ZggckzROWYn3MYHnbMj7rLzbzMDjzMTTzMDT9mBp3mJaDGBp6kxKwSYlX6l5eDmhGGy4xAzUhFzArBSaEYwmJKIk0IRY0IyMzIxGbDpSTMjGE4HSkmg+QTkdKRNx0oTgdLU7GTGcj5eeDZ6nQyZn4+gp2KmtBH0Gfi57QR9NoIyc0QfUSiDKJRR9RUYZSVIH1dKHU2kD66U4fU0ohYaiQqNMI2VVSFZqBKy1UnaamRrtaK3VVCVbXi15VgpZbAWua6WupYDFyYi15LIbutlL3mzHrzaTGHaT11LYdxbWewK4oMCW4/jnVJgVyQZEvCbDuqHIl6UYd6TZkvyfC3xXoWCT4OBW6VhVmJwa3QsSwyuHX53Fss7i2cBsJg==',
            'EXIMgGBwYW6BCGES0iJGRpFoyElWjISVaIiTokRJOjTLTo06SdNMmiJpUkZGkWjI11oqJKknTTJp0kyJMtERJFJ0ad0iNFUsiRVLJJ00qkiJMpKiTOujTuuiSulTXSTLWWnSVUnTVUmSVdMmr6ZEoyZNRSRSqSV1FpFKLSu9S61XVWs71JFNddT3VU9lEns9anvWozVKM53LU5iT9cmzXKd/1Kd1T/971d1yu81u//2K5rH7/+4/96/d82uZ2G/m35nfz3vzm33WV8nCuVh85nc/i8tbN9TeZP9zV8RZrVfbZbbZXKw542Zx7TSsa1zJlG+rj2+dMy70rJONHOPdSMu80OcfaucgaUZ9/qqCJrTQwNCaONuqWNnTTRdy08vRVUjcjVTNPWS9q107UtbO2Ozpalrp25betpdjQ3O4r6029TZW9najeVtXc3d6b6vp7y/vW/uaU393g8G/pXBw7nh4Na4WPa8bHrXEx7Xj5tbxsuxcfNr8rTsTj6Nnm6ta4+rUnP1bfJ3aU5+rc8zfoedr3LncNC5u3Z6HDU87fqXQ46l0OGk5/PSh09+uzuuZdLhrXQ65l0eOp6HTO9PnoXO6Z3p9M653PN6fXOufzzPQ6ZfR6ZlzOeR6fXN5XPI9HnjeZ1zefwwvL75U527B5PXI87jeeRyyPL53k5PDHY+++uRzvvF233j8bzxN114e2/4e+28PVeW+3Wzh6rqN3qtHB1WndaLi3emwbvNbTbZa7us9mtMdft8lhbHFWrTDV7DFWdjeq9XfqVfeqOpt03VXKZqLFFaa5S6WpQdHaomipz3QVaCz9SYZyhQc5TmOamzKYozqWlSFlJs8ysqMsfHm0jKjUbFlLGRoxiochxEKNREKNwj+Lwr+JQL2I4B3DoB3C3txD3x1A3lrB3hzAnZi/bo2gTkvetwaPZwXPdsXvdtWum1K3szrHGzqXisyluFiTuksSZuWBG42BM21tDAA0n4=',
            'YWsNIGBsYWdtbt1Jt07rlMlVtjVshlKlc7jdLPdMhMblcKjkYPcrPENPB7jRahJaPJ8MZbPJJhJLMRcIZ5FmMCTCRTNIxkshD0PAxloQZbEGPQwxbHGJBSDQUw5DQMQeByDGOYcYshximGIeAwxIFEGgUYYhDDjDwKGFgUgwhJDBCQGGHGGgMGHIMMMIQwcMYwUIeAgYYg4wogpBxA4xRhBBhhxBBiDCCEGEDDkECEIHBiGFCDDDDDBBiDBBhBhBgw4gwgwYYQcQYIKQcEGIMEGGGDDBhxBwwwYcMSAAKWo3l5E1KshaqunmgqiBo1c80lQ2y1I8yKmZZKmm15UTDLSzC2TjLFUkquFLLLGjlmBRiatoxVaUQmr0MkrkIor0EgoFAJqlPyCon5FNHY5Wz4kkjoYqjoijzoaoZuOSk6HpY2GJFNxqUTYciZqMTZqOPk0GpMzGoYzHIc0FoowIHs1FIovIn2aCjxLyKDMhh2MSCCMBpuMSKDMBpomJM/l403mJQ2S8cdZkWNZePNExKm8xJGFLyhoJqVNpLipYJuWOpLjBMTgseZeaKxwZNRibLZwcNRqaKZufNZscK50gLxufLM6Qlo8RF85RFY/SFo6TFtATlY+TFtAVFZBTlpDXFVQlBYorIpoikrpLQq0ZaVKW2KqkryhTHJZpzIpprsoKk3LpUHRIVR2XSpvShV3hZq0Ek1l8ZK1EIa3BNtdjEJghmWvSSmxxipYpRdLNLKzLLKzXNLpaJ5Yts8u2uiXVxolS31DSudUq3SoZnWyWV3qmt7uFlerBmfbxpv9owsBhN0DcLphMRuhb5tw+Qw4nCd4rGYWMznuQxm1jdBylMpxZDUeczoOLI6kHO6zay2pFz+02mZ2ITRbT6Z7egqPagWh4IHT70bpOKJaregqbklRr+CE1HNImx5pKs4o02fRO7Dkjdp0T9r0TJtuSft+6h3HGAH02',
            'cW4NwGBrYWqBAWESQxA6hCBlCEDKEMIcKcY4c4c4xgyRSiIDlFSHKOcOcU4pxTCnFOKYVAxhTjGGOOYU5DCnHMMYdBCDKKMVJijoIYqBinQOUiDFIYqDGKU6CGOcxjGOg5DIOY5zngWCTkgmBYpgWJopiOKoEog5rHOipZHkihpHmehZpoWh5nsaiKHsaiMHmbCqDyyg8qse58nqjJrp0WqdlsrZLr2S6+msjx7p+ayfnuj6Mo6jR/J2jqOo6jifI8nh/q6jyGL6Zi/n+r6XI6lRXDqs8dy2JchsAE8JKHd9VK3PRT3vJSt93Vd7yVLhdVffc1a4nRb4HNWuNzXrhcVdkdWKcPgt8vqwXF3sFyubF5XBinI4M/O4sVx97RdDa08ng0R0drU5exqh0drd5mpv6OxuudocJ0dbmzszlOlpdPPzOnoZniOlkdWflfo6WBz6GWEujfcp0cMP0Lz16V+AnOtwnpXIHn24adCxC8+1ERz6sPzq8Zc+pFXNqxnm0Yyc2nI8ybHTlUpDzZUp482UubMlPFjy1ypUuxo8xHHiTHix57xH8xcSJQXDfzlwoFB372g8B9QTfuqbvHlB3raq7x1Rdw0qLctqrtmdR27Kstmyrrar6i2C+0tkuqOvVWnWrq61ya4tSsr9WlurSprPUJriaRJbqRFbRoEl80R+4jOI7zoDt6mD15GdPX+WOYOXN4EyxzA5Exh5Q3gWNLZHIGL7ii2VxZbC4ork4QnjcSWxuAIZHBlcvAEMbfSehX4fjV5Jad8G41dCWlvI7M3MhobiNztzH6FaxujcRunaB+dLaM1TMO0toF6VYyGmZhWtr5DRsYzaq4O0a+N3ayNz62P3auL0KsEN2pjdRVx+tFQHbSpENKU8fuk0hqaeR26QQ1tOJ7ZGIa2lFtzRSGqRy+/QyWjRC/DQSunQjO+PyutnxrZn5jaTszrSfHNhOTWxTw9tjg7AAEzf',
            'wWUOYGBpYWGBEGAwqg6Qqx1A6irCqFWHWKsVYrQ6h2isCrKwO0dgdw6xXjsDuK0dodx2ivHaO8rg8DtFgV4dp4iuPAO6Yh3XEO+YiwPAeJ3jyPEeB5FgeRYniPO3loeEzHjcyxmZ4lpcC1uJZ3M8pnc5ieuxmcymmzPO5TT5Fo2RabO6XLaHm2c0+U0bO57TZbb4zZWJ6qyLVWN0bO5vnc3zuj4/b4fVsfo2V0VhtGwfTZLy2KtNerX3Po9/1Vd814ti2arnza9eLYrvfFWD4Kwe9WD4pXQAyLhrZ0f2k3QamcINuaodUbpNrM0WomyfWpok1k0U6cyT7maK88YKd2aLM2YLN2Zrs+YLtcYMdDM2WrLWWeNGutlrXNmbbTlznTGTjMpg80CYOcyTGBnExeZsxh5mYPskYxM8Zw8kYxskaRczMZWCNo+fMpl8m0nKzWhhzaXhJvSxqbz8BOaWKN6V5nlXFHNW7HlfBHla9Htu9nte4UC7fz63Z0O7ekG/ZkS5d0PHZ0a/b0jJXkbDb0vPXkrHZkzRWk3JX07VXKjmqyhtqtUz0yqbq0q6qCrG6sFY10Na30lXNlEK5xnqw7qQr3CYrJyolh3zNn5ziycJu185Wz8p03c5M29Ju38ZG49ZW5dJG68487dZG78o299408cI1A+Yk974lB+IrgOEChe0SheMDh+0Pit77ie0Kj+D3jOUFZHk8GR5PnI8HtMcXXK7ntM8nNM63bneDozm5w5/W4qHe56LS16Pa5qXQzWm1NzUaWTq8zeqtDHrcrRa3OyrHEzq/KwWzxMO0wsTaYFyba+wG3vLU3N5fXNtZ3lxY7qwsN/ZVrfWFngVk9gVlnh01CcKkpHFpp04c5RY1FM8eYoeNNS2TMTrkSEnky0ry4qR5chH5cRGuZDR2bDRLnQELzISLz3iBc58is94eXPdIbQcwDG8',
            'gW8PAGBqYWuBAWEU001bJpPqnqpRei9FrLzVqkopZeitFbr0fZer6rWfRS6s3YWo6y1mVWuyqt21fhtFM/mrr1VLMy6jNMm3TKMyyrMst/DL+x+v9+n3n5956nN/rzPr8v7W691y287xy+s8xm/dXt7dr91jOcazjOsX1q9+Ztber03q9eYvblb31XVr27a0/XrTlMW3LV8R5a8t1zHVMR7S0fztDs7x7C8tx1HUNQ3LBuQ1DJuQub0MH2Xccj8jgbsbk8XBeluTp7i+Pgbpri9PoTR9i6JseACdOB1dBwgs9ueTotjo6DI8jotDx0GBpOixQWiwMvQWHnpLjadBWbOipNJz1Zw6KUyjoKjRz0ZldBMbecjLPPRHFzkRXzUBtOcgLWYfMpzDhfzDxdck0X8w2XXJNFnkmC645ktZBYuuKYKvHKF1wyxTxChZ4RMs8IoU78kYRwCZKvyJhN4SJu9Hle6Il03Y8k7YeXTcDyfajy62o4mm0HFqxHFU2A0otgOLVcNJo1Ywv1Y8p1IsqhqCBSpBJVaceVTQjCvRjSyZ8eWWdGFefHlkzI4qs2OMcsQJoy441ShAmjJjzdJkiaYwgaWSJluIIGEY0oYoYmXTEEzSwhYwsGUM8EVNov5ku34odb6cMK8lTTezh1XQyZbwdOtyNm26Hjitp84lxPHW1ojqtp46rSmPK0IT7Z0p1WNMhbImOtiUIUr6o/L6hEhXFp8ripGhWV58rC9MisLz7U2KfVWSBVJqnSotEenuEypzVKqc6T6U5TqmPVDSHidpD9Q0d6qaNDUNDgKkokNVoEZWqFDVs/lLVQIqpns1ip7IVZ5OYqdTVqnk5jHE9ck7ps81ors4qNFNqjFm1VnmllozSszSa222Z3GmZ2XCJngakyuOFM8Ddl+B0prhb5bheKaZXGX4XimWl5GGJ0kw1wMyxumXbIMZZXiS/bBjHQ/Zhug5lqhKYb4Arf0=',
            'gW0PoGBxYWmBAWA2ktp7T2ntHam0tI9Twj1LKXEco8S0hpHaGUdo7Q2jlDiGUOIZQ4fhDh+UNn5Q4fpDZ2D+oZO2fo3SGjdIaNyfxDBnEdFbTwTxTBO08lbR0XlHZeUOF3R6XlDJfEcGbOydk3R+jcn5L2fc3Z2j7mcQuXtHBmjsHZO2dY7ZuEMGaPuds652j8nXP0ddDZmEcGaSsZtGx2kbm3S0dVDR9UdIVP2jZDCOTqp7Oons+iejrK3OynRHSVE8oVUyjZO6Vk8J0RypVTCVVMJ1UunRa6NWKoYZojZiyVWLpzWuvA4xQIz2Rsw3v1M90eMd8NmfGLme6PGvSIkz3SRN+kdJnwj5x0lxrwjqcd5mcb5Ocd5kd8ZinPaZHnKYzztPj7nNzzpP0LnRzztN0XjUj/tOaLyqSJ1o6JyqaT1pyNwqNL61ik8KipvStJnCtKHKu07hWKpvsqocK8r7rMqcLbWdljV91wruu0qzuubDpuFa1XWy672v5rjZNmAs2O62XTf2vHgLRnvbdhwtry35xv4i44sCuN/HO+DCXO3kb1fwl4sZd7u4d+rZ98tYhg6uZL/Wyhh6uZwlPLw9HPRdHNxE/Px9DPRcrPSc/RyEfOMpM1LKRs9MSNVLxNFORNNNRNbn3+mnYmqoXevooGnone2p3WfpXe7qW2g1LrbVrTZ1TTUa9tt7BfqrBls7JftrRdqrVdu7ZVr7dbt7lRsN0o2pu1GsN4k3O9Ua/AQ769R6jiI93fH9fjIttgnddjH9jxTe04x7U8cxtsk9rsgrreUd2nKK6vLL7bLL6rNKbfMLabPJ7PMJ6rQJ7POJaLPJbXoEdHnEdVpD9LzyWo6A7SuiP0DoD9K6Q3PZ47TaQ/R543N6Y3VZw7J6YzR5o/LagvOuWOzHUGZXlj8r0heU5o/IuaMx+gPyDlDcSc8fjOSNxvOIYLIHY3mEMFjDsDzCUACLng==',
            'kWUQQGBhYWGBCCESR0YolRMjBEiYoSrJAkckEzihikyNFOjBaInWaxRm4o0WC0TF0TJapk7Jl7oZa6aOjstXZ2dls8Oq391t8O7z7Pfs9bDzsvWx+u+49bX3t/e2+HSfnHZtTz7eVn0XPRZ/X0Z+lnYf5hbvlmaP+8P8+MLs4XVxfHV4vzwX9QF9UF8VFQviwXxYVIqCrVgqRcFSLBWK4VRXFYKxSArFIFcVgUpWBXFKK4KUpAVwpgqhRBWApxXBThXCmApQpYC48GM4o+68gjh8Yld8Qlf8Uld8Mpe8MpdeAVu+CXtO/KXa9M23fF7XdGba3pmzWxqyt4csVmbsrcnbDsTtWtUFdbA9UdkhsdYjorYIrHVJZ7rUld0qic6xNVWiVTjUKKaZ9ZOqZXRc4tmrQsKHNrZqzjKc5lnMcuwluWcTXKspKyTqU5BtKcg8k8c5jpin8lxbyLxECOsNAirCwolCQ4yYGHCcDHit9iwW/SITeJcNvcd8rrQhbtJfK5UIG6Tnqt1J8rhReFspvULXUeTVXdotFZ0Waw5RZbDhsVx02K23a9dbosFxuVq+2RXb7fWcTNrGFqqxkaNTxMUquZtKOVcip52mm5lzT9DJUzUuaXoYNK2LWla17Rta1KVuW6FrWpR96rQty1KDvUKhcFjP96dUDipZ7yUJPuCiOuidCfcE8bc0qJ90TZpxSpPeqXMuSNE77IyZc0qE36ISadUiJp0RZp0QKZdEamnM8zHsjUy4Hsx7oETPggjDqbRMeaLMeRtS/mfSZcTmXczqmfA2kt5nWZ7TTL+Z5mOsypjzNqY6zeYbjCmW46ky1FmY7zbNMxhTHcZU1zmGZ6DCTTSZzbKWU0zmVN8hXNsphJxiKxxhLpOsZZTm8Xjq+WSeXSrPL5Zntksp/dKs/sFUoNkvH9cqlFqlFQa5eR6BNUOsWVJnQHRY',
            'IW4Q4GBxYWqBAWAycW4oyZijJmJ824o0XerRWKck5qyTknReB9l4H1XifRWaM1ZH0XmfNmpcWanyTmrQ2bNC5L0PonNOZ805ozRmnNGR9FZlyVqbFGyMj6JzLmvMeS8y6KxLmnM2SMjZpyPmjEuasyYJ1LgnQ95tE4lyRibM+CMy3ozPgbFORME4lxRcbM9x8DYIvPiW4+CMDXGwPabE9pb03kuTca02BrD3GuPaa01iLi2ItLYew9ZLU1krRYaw1SLS0nsNSew1B7DUGrRQSpNJaU0kpTQOhc4qFzkoRMadFBZkTFnRLCjDFNIolVSJ5aTZpJKRNLqoyiZTJRdKjJJNQimNVjk2pQyqq8Uo1iCVaxBLKtPyeuPi6rjso2B4XbA6KNicldkbF2ytyjZ2phWloTmtkZbUxKtvYGNuXFm4rjG5rC7c1Zlu6suXdQZRe1BkvSUwl9TmaARmd/RmFg0ZswiAymHQnDDHzKYo6bMWeOJjDZkx5w8mPNmjJGTyZMwdMsaOOWKH3MmTtNEz7mi58z5M8s6URVETOOgJJKmJnOkIpuoIHemJpzWDEC1BRLWAtH1hNJWAtN2ZBI68cmrgan7Icm7gYorcemdyLVdyOUV4OUd4LVu/Hqq9FK3gkVdgilvgEFi4otaOCRXeOLXPEJL7IFLjjFGHlDGFjEmVnEF7xiTU5xJj5Q9p5pZoc4e1eYXbegSa2WZcWiTavONOToFWzzzbs6Rhw84y7Okcd2cad+keeWgdeWgffekffWegf2kjgeghfWilgvRSQrOTwLTTQ3mKYlpKII5iyOuirhWasj2cwinNWRnltJJzl8Z5TOUcxrI8lpMeU5kDkNZvkPJXjOJxx3svxHs7x3884MCd4j+fYMSj38OfYUSl3UegcGPUW5l0RvY9R3E6pXEmqbelV7abU7SfYrOpU7KfaNhXrddUs1bXsutr2ars2qot23VWrPR3YDo5',
            '8W4RgGBqYWqBCGEQXxcBsHoG0LI/gtlwH0PYuhaF0LQuBZFwLQeRdFYLo7A+DuHkWRXCyLArh4FcOo9BzFkVQ7lUOodSuDodQdDoHQOpyBVmYOhUHEOxQCqZwqmcOZwDmUBSI45DgRxRIwokcZygIxmEeCiPBQ4UMFGhg4wMM5jkaCCJJBEkgxoKIeRhFoURJGIYx4GMaBTHgYhJIYkDGLIkDwHMahDDwPIaB5CyQwtDQGkWQ8B6EgPQeRaCSNIPY5g+jEE0SA1iSEwSAmC0D0JQaw1hpDaFkNB9VIEB4gQkgPcnFy5/r1rbX8D+YLQsMeFfeC5fMuG747t6y4l6Z7o9cmN8dd/558Vt1YXu04/Vsw2vXlXPuwDo151x78Jzbs63t+Oxb8pub86b3LGNjfqTa5Yqvy1dXjlqfPQ6fTN0OOmndc7nc9PI56eb11cPnocrrq4XPTxeupnuerhdtTN8tmf66FL89kd6amV562Y57Mpy1qV6bGS46ohz2pIb9ZHumxRzbsxrprY5t2sX4bMa261Fd23F9mxiW3axXXqYjr3sR16lENG5h3VqxDPuSGs2sh7NtSGc2zDeXZhnFsUMY9rDGHUoVwbcM4dShO1swxh1pCNnWwtb1wSta0QnZ0wTr61CVjWwjU0KE6muCNPQkIUNOEqWpQhN0YQn6lCEvPhCZqYSlZ1B6RnwnJzsHomdEJR88EIeZQhDypCUDNhGDlSEX2VhJ3lYRfZEhVxkwg7yKF2+NQi2xsMtsTCLTEw2zxKEmGFhxlhwotwIhxfgwyswKG1l5Q4pvsOK7qQ8mvKHlF3EElxIgmuMSRXFEUdtRRDahRBcQi6GvCp22iNnqzGTtxjRqmo8euJGy1JkjlpR4tRUmasMkUopLGa2VJ0lMFqTNEqSmS1JnCE9nidJT5GcmCRocIhORhkZvHHzkxh8xyiExyh0xMwdJ55Cas4VHWkSl1MRAIuv',
            '8WsSIGBrYWdgaQmiSEwPgaQuhrDYFoNgfAlCcD2LoPYfQth8CYJoPYug2jaDaLgTg+BuDYG4NwbBPCYLwThtB+G8Lonh9DeLwXheD+G0Zg3CeH4RhODuJgji8J4dx9DqF4VxOFULoyheFUN4rk8RReDpH0Ms3CpF4VZfHWOxVDuRRWHWZh1FcqiKMxFncq4MRKDFSiw6cmKuKRvgjjxk5KOqKUWkjh8k4rkuSUlSSolBdkoKqnNKa6JVXNOq6LqisqaLC5JaSmnddk7JYTsvKOy8orJ6XdCyrSO0ADrkSENQlHNYTIQ2iMU2BUhG8Rh9wRHd8lCThERvCSgLlFw1yjoPnHQE6x0G1Dn6O4e/9o+AvAe7fMg/XmRePqPeL4Ju34IO0+irn+EHa/SzZsCTtsC7RWhN3sjTJuSjhWZxq3ZVrOjjNF0ZZl8baIvTrHUTjNqB9gqmfY6mgYJVkS/VkK7WEq5VlEta2oXNbSq1XVCyXlCtV5YqaSUq9dXKWllilry9Q0yvUaQZqNNMUypJonk22TNLNErTbtLJdskVOO0cm3iTTT1GqefIynHyJU7CQtPwEMnIqFojDQNPR0EiMc8qekIZEJZ1URknyn5x5KJTDkiNE/ohPNyI0DqojUOCiFI2lEapzRCubKIVzSolXNSduGmidcxJy+b0RtGJO3zTRDAY07fMFO4TCp7EZKbyF2nsZnTOQrJ3Oa0xmKaa0mNM5yultJjTGopJXUXaX2FtJbCultxbSGwrJLiWVIaywpDmUVd2lpd5lCubizW+ZOWeBaV+ZVrPImVPkX1fmTlDoW1XkUnnUtqPIrvOpSfcy236ld7yK7PsUnPIs2PQrNOpUseRX/9S995k/5yMj76E18czQ+OJN9eZn7cSx4ciz58DJ2cCi7+BsdO4o9nA3Z9hY595nx7DFl2Gjf1F1wbTg3M5fvaznYzGe1nOGtoMLWyQACVE',
            'sXASwGBxYWyBAWA2ZMPalw/qPEGpLxcixHqTMe5LR9ltJ6WsnJcS8lvLyW8u58yZo1LqjUuady5q3NmjVHKMT8pzRurVGauUZq3VmvVPK9V6p3ZurNnKsWcszXy3NeruVau1Zu3duq936t3ZrDdfMM29uvf27V+r+W6x5brHV/cMXcx1fvLdudPXYy5hnHmWb95ax5jjHmWcOZXx9lfL2OM+5Yx3pvDOvccZ8zzlrPeWs9Z70znvLWec+Z3z9lfTmWs8a9xvr3K+fNMZ7zxnvTGW9b492vhrbOWtM6Zy1nnTOO9b471vlKNaHxpZjHUxH6bkNdLCdpGA8Z+E7xbx7lXjxi3D3FuH6FZQODZPUC0iz1M9HLSPN0kOaqI4vTREvORsrTSCTlo2UnpYeko8nNUQ1ISZCOnhmQnY1ETw1EUYrCUsYhKCJwFeKvk7En60iTpVCD1axBuqIedr2H2yshtqvYdbLcNMF+G2rEhpetULsGkGl6+Cixmw0tYsJKmxDCpgwkobwVUs8JpG+E0zWCiRvhFG3wmhbwRQusIoXLCR11A8gdsJnHUD5x6wibdwQMv2ETjxg8Vf4TNPoHisFQmZf4PEYGEjMNQiRgQQLRWFSMJg8Ti4XJQ1CA+MwqTiwSGyGFikZITFxyGCUlhMZJUMkZMFhcpQwRmQaFymGSM1Q4KmsND5uHRs5Q8MmsPDaLDwycomPoYeF0WLDqKiA6mxcZRUWIU4WFVUjZOixcTYY6TosaG2lIEaWOkLakSNTIEraSxGvkiVpTBS1lyVlmS9xJsjajhi4k8Vux8xaTBL4KEYuIxTN6im7yMc1epJ3CjLO3qadxLMQYE0kGGoIMSNRHiNVFiRrpcfZSY3ZT5Fup8buKcq4FWR4VWZ4VmNOZbo8q/G9C/U9LHIutnoe1nnXe1zrxa6XxcZk9W+p9HWhe7vUvp7ofp7pX2/1r/f53/h7NjB0IsYu3bRYABrMw=='
        ]),
        bitsPerSample: 24,
        channelCount: 6,
        channelMask: 1551,
        codec: 'truehd',
        expectedOutputs: Object.freeze([
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 0,
                pcmFingerprint: 2073784938
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 833,
                pcmFingerprint: 2440426600
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 1667,
                pcmFingerprint: 3830822120
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 2500,
                pcmFingerprint: 1721728980
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 3333,
                pcmFingerprint: 630060173
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 4167,
                pcmFingerprint: 2684207396
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 5000,
                pcmFingerprint: 126846538
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 5833,
                pcmFingerprint: 3024754755
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 6667,
                pcmFingerprint: 2258451402
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 7500,
                pcmFingerprint: 2935556977
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 8333,
                pcmFingerprint: 3943144767
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 9167,
                pcmFingerprint: 2018288781
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 10000,
                pcmFingerprint: 2091400628
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 10833,
                pcmFingerprint: 1814356104
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 11667,
                pcmFingerprint: 2561028803
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 12500,
                pcmFingerprint: 2705566327
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 13333,
                pcmFingerprint: 3429889287
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 14167,
                pcmFingerprint: 2090293059
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 15000,
                pcmFingerprint: 833790854
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 15833,
                pcmFingerprint: 4257389917
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 16667,
                pcmFingerprint: 1183377187
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 17500,
                pcmFingerprint: 1866280021
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 18333,
                pcmFingerprint: 3593002694
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 19167,
                pcmFingerprint: 3438112426
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 20000,
                pcmFingerprint: 655558784
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 20833,
                pcmFingerprint: 3651929410
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 21667,
                pcmFingerprint: 1812148775
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 22500,
                pcmFingerprint: 367500690
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 23333,
                pcmFingerprint: 2226107210
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 24167,
                pcmFingerprint: 1495609467
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 25000,
                pcmFingerprint: 317611895
            }),
            Object.freeze({
                frameCount: 160,
                mediaTimeMicroseconds: 25833,
                pcmFingerprint: 3481641535
            })
        ]),
        majorSyncRecoveryStartIndex: 1,
        sampleRate: 192000,
        source: 'truehd_51_side_24_192000.truehd',
        sourceSHA256: 'b6d447fd0d80c8fe1b624742cb64cd2161569eca3c1f0e32c292cc6404e369ce'
    }),
    Object.freeze({
        accessUnitsBase64: Object.freeze([
            'gGL/2Phyb7svDwABt1JAAAAAjH8QBVYDAACAgAAbL5IgUfHqAAABEAAAABKtQAAAAAKUgiIjmgl//rpf/5JQAFwAFevmBgNteWS9x8LekWM62W1m6svBjWqTAO684EWg/oRZIgG+PDCaiOa8iuaJgk5bAQEIAAC748L2yM0Lre4cmNvkOhEMgAAR899vXTq27st7Dnw1rtyrQu0YsqrHivpsF6xiv2qeKzSpIKhCcYn0JpSVOkzJM6MKijIQaJGfhoOsjw==',
            'wCwAAGApkUCA0CCB8TPRx8QOyB5MOR57LNpp4LOBZ1KOBR0HOZhzFOxJ0FO5J2FPop0FQox0CRw51BSYyBBSQqPCSASdDSISnCToipBVISxDWQS3CX6VpA==',
            'YC4AKGArgQHgRRr5EyUjGRNdGzkriQNZM7kTjSvdK8Ej8SwFNBE0RTQ1RG00WUStTHVE1VyxRPFs3UUFfSlVIXVJbUF1fYVhhaGFfZ3FjaGl0Z3VtdWeCc3ka7k=',
            '8CsAUGAogQigQLhYYWWHhiJ4+mInlrYquUxkr5XGW5lr5JmYtlHZfWU/m2Yv+eUwn82rhX5V+HXxauDSYde/r3xLfk1zTXZPcUS3ItpRLKjWRGroZUY=',
            'MCwAeGApgQHgOsalfas5VfSs4lvCsYdu0uXdmvv1linvUF6ftzN+Uux12Jvw12BvPeB4uOmBvvNF9mvr19gvK19WvqF9Oupd5FvI108vH901unV0vABiDw==',
            'wCkAoGAmgQGgO9NOi/4p5MvR/cv8IOCbsc0KfBXMq5FtCPca0IdRnIgzHMhvAfxILx+8euIbSOwisK6h+syoIKTOconNpCyg2gNqDl49lPwYdg==',
            '4CcAyGAkgQGhEfAVCAl0CIQJaAuEErgc6D2QSyLYBrApUQwLSJWJRPVPOiVjMqSoMtRsL0OtK9PvHYN5I9KZI9HUlejKR2hVIro6sCLV',
            'sCgA8GAlgQHhFRqUqlKqSLUjiNPR/I0Wk/RJ6NxCmJGkCUlfPqUy886nWH3UrqJUj+SKkXiR5H0kcScpfkvaXZP8mvUepcFPKitRsqtAl2M=',
            '8CIBGGAfgQihDBqg2gpgXYcQJsKKLYKHEoKMMOIYoowxIHBiRiDknMJE8Q1ixHuSpLEwS8dFzfZ+X7PuWW7p+f/AaLg=',
            'kCwBQGApgQHgOlREqHmRc2NmSM6QnylCSoTVCUp0FGdp0lSgqU1amqV1aosWdWut2ta3t2tfAuW9nDuXlrKvX9rKv5drGwaFzIu6l7Mvad7Uvat7VAB2gw==',
            'sCoBaGAncGvd1sOtd2MGve2sGtd2MGzd1721g0re3hzrW7hy7Wvd0Luba0L+LWz7+BXy7d7bvq2Dbsat9bqqdzYp6lfVoKtNRmak7RlaMpQjwBvn',
            'wCoBkGAngQigRSwdSFJn69/rPlR4teijoY6WuBjg82PtXrP4zOMnTB0wcLrKzssLrCqnoqap6KimljpyKROkTJAqLOhxUWY9iosc8CoIOcxT+L5i',
            '4C4BuGArgQHgRXHNcfFxzWnRYd1htVHtYa1J7UmxUeExvUnlMdlJ3SHtQd0aASnpKg0Z8So5GgUiQSI1GjkSfRopCr0qPQLFGokiuQrBGtES8Rr1CyUjCQtcbzU=',
            'EC0B4GAqUjKQuFM1UDqUOJA81DvRP1O/UkJTwRLFU8QTyBPG1MnUSxVLVc3UzxXQFtCV0xbSF1WXVZfXWFgY2ZhZmdvZ2xrdmd5a3lvfmuBc4NxhnOLAANcQ',
            'YCwCCGApgQGgQbxDmPaxz+Rbx0OWcyEmXcyk+YfyU2bjyFGckxtOdmxdObrwtGZtw9WQuwl2Htw+F+vwON3xv2V0zuels0tmtp3rulk6q+tZ5qO9TAB3wg==',
            'sCsCMGAogQHhGtJWwl7aRsrFxbtu7itaaX29r5f/XOd7je1XtN7DfwXrF6rgn3Z+CPfh3juA7cLYSV0bvD2AUti2AO3Q9fDloKYQrYCmAH7APXgdpc0=',
            'YGQCWPhyb7svDwABt1JAAAAAjH8QBVYDAACAgAAbL5IgU/HqAoABEAAAABOtRgAAAAM0giIj+gmAAk5f/5MP7/7ThCam/Mx2WwU300zRxWv8sduP0Gz0KC2RV+k0SwLsFDPNxPtIgG+PC7xjvy2YunRgP5VgQDIAADb48MWuFnL+S6MFzvoOA3QgAAOdY4XKFwico3ON6mfpXieGogKYyiErk7I2ucukbqG+awpMKHKqzqcq/Wx1s9bfe02wObvbB8xtsEAAAW0=',
            'YCwCgGApkUCA8B97KrZN/JtaF/Mt5l/Wu5l/Zv6uDXu62LXwbGDXxa1/Zx62HWxa+HSxbGLNx6uDRx5WLTw4eTQv4WPJwXuPFv3OK9v3GCvwWl6rwVbGBA==',
            'YCkCqGAmgQGgP9qfqD6i9m/JP2Z7i/I/qG5he3/Z66eNnDdw1Z9WfNk0WsV3NQvVcUW9TtPrkew3sQKTKsyoL6CqgulIZiWMhiH5Bx8biEyWDw==',
            'sCgC0GAlXxx0NgF2Q14QZEGglgPZEVQhcQTBVBNQIQD0w04OTFSwlEeMCzBw4ZHEzikYWMKxx4cuIKRC8k4BLiEAI5ERBEgJGDUQU8AABBU=',
            'kCwC+GApgQHgPRrqBURNJ9cROR9mQvB90QQKB+Pxp+AQTh2JRUZyaQ056lQ2J6wQ3J+0RZB62Sah6+R7CDLR7SPaRayXoR7iTqTcqXvT96btUein1ADxJQ==',
            'cCkDIGAmgQigOBPMF+Ab4B/sJ8g/6H+wn+L+hvsX8F/hvob8J8k+T/RfWHlH3P119Yc1eqvRXfzzU2+bGNrWX7Y3k+xf5DL/9wpfNr31oAAHhA==',
            'MCwDSGApgQHgPm2EuhoUsycozdCRoy1KCqR9N6qw9RysPVZssN1hmsslpgtK9tdtKV1TuJN1LvJNw6xJFswxolwtxnt0rxmmApxF2ArxEGEvxDOItABzYw==',
            'ACoDcGAncQ7hI8RBiI8I3iJcI3jJcJDgHcZNgIcRDfK745iMrg/iMrhRhNbZRfPbZTfRbBffSa5xdTK57bT6ybZT6ipYV6izUXabFUZaDFUcQEUN',
            'YCgDmGAlgQigOUaU7qo7Luz3paE+/LRPYhSO5IsleS3Z3UvumxO6pr096m1dSsnY0s420beFoa8PbkvyXQ94S+DXpcEJgDX4TBEwAbBAO+M=',
            'MCwDwGApgQHgOXXii/XYKi6VYCezUX6e4T3SWuS3SWuSWiSqR1yOrRUyKqRTqGnQziKdPSiKcPSaCPQyx2BQSCGDOwaGCPwJ50RQRxqRPR9sPuCFrABGtQ==',
            'MCkD6GAmgQHgMQKECdCjQIkSFCYRo0JBGgSDUh9GNSk0xFMPTj041OKVEE4lWJVjlQdcMVCmIxaKXDGY9aIbllohwaZCmxlsSbnXRVuhdmzs1g==',
            'MCkEEGAmgQGgObYml99ldZnmyFnedY26F4ldY3yd+lgKISiFpj64iuYri75+uVxnraXObvsdKDK3zpNr7Sr2v97ri83wOsDnH6wPdHjA+1zT4Q==',
            'MCwEOGApgQHgPt497Uu6N3Nv7t7Nv7eDRwb9/Ow7+DQw7uLTw7eHSxbWHPx7F/Py6V/RyZWHSxYOHPxYGHEx4N66yYV6xxXd+wwWN+ov1l6gv0luZABhnA==',
            'QCkEYGAmgQGgO/nPJPuO9kuYLyL5e+YHhy3e+GjVy1XtW3NX0Y703RftRMlOw+wR6zyw8qNrDOcyrLJSicrlIZCmMajIIReEagGHQyAaZCSdbA==',
            'gC4EiGArgQHgQfptugXqdcIFuknKJaI1wjmSIaIxmj2KLYpFgkF6PXJFenVSKXqVUjFarUo5Wsk6WUrBIpFSvRLFQt0a6TLtEvkjIRshEy0TTQNVE2kLfQOEhac=',
            'MCwEsGApgQHgPRNp1nRO591PPSGDPPyGQPRJ+XPyx+fP0KGqOVCKvPWqK8PXKHEQ46HEQaKTNP7SXWQbibfRcCXpS8STwT8yf0TeCjwUfCnzVfiv3AD5qg=='
        ]),
        bitsPerSample: 24,
        channelCount: 2,
        channelMask: 3,
        codec: 'mlp',
        expectedOutputs: Object.freeze([
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 0,
                pcmFingerprint: 3440316975
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 833,
                pcmFingerprint: 3309928800
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 1667,
                pcmFingerprint: 2905736093
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 2500,
                pcmFingerprint: 95143458
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 3333,
                pcmFingerprint: 2120611621
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 4167,
                pcmFingerprint: 132863271
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 5000,
                pcmFingerprint: 1656457218
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 5833,
                pcmFingerprint: 485789925
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 6667,
                pcmFingerprint: 4064536417
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 7500,
                pcmFingerprint: 3510586491
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 8333,
                pcmFingerprint: 2952319133
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 9167,
                pcmFingerprint: 4216000251
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 10000,
                pcmFingerprint: 2532736829
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 10833,
                pcmFingerprint: 2361293548
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 11667,
                pcmFingerprint: 2996555997
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 12500,
                pcmFingerprint: 1779084996
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 13333,
                pcmFingerprint: 3412960468
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 14167,
                pcmFingerprint: 353080358
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 15000,
                pcmFingerprint: 942675713
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 15833,
                pcmFingerprint: 16664584
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 16667,
                pcmFingerprint: 3921123299
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 17500,
                pcmFingerprint: 120136985
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 18333,
                pcmFingerprint: 3936456578
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 19167,
                pcmFingerprint: 2008911727
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 20000,
                pcmFingerprint: 1209849231
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 20833,
                pcmFingerprint: 2271531204
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 21667,
                pcmFingerprint: 4291289326
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 22500,
                pcmFingerprint: 1455427411
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 23333,
                pcmFingerprint: 1177292565
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 24167,
                pcmFingerprint: 539449659
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 25000,
                pcmFingerprint: 1369213016
            }),
            Object.freeze({
                frameCount: 40,
                mediaTimeMicroseconds: 25833,
                pcmFingerprint: 981034830
            })
        ]),
        majorSyncRecoveryStartIndex: 1,
        sampleRate: 48000,
        source: 'mlp_stereo_24_48000.mlp',
        sourceSHA256: '0a8ecef742d164ad74d99576b22e4688ef76e899ca36ce601666b2c8c71d1d72'
    })
]) satisfies readonly EncodedTrueHDExactCapabilityFixture[];

function decodeBase64(value: string): Uint8Array {
    const decoded = globalThis.atob(value);
    const bytes = new Uint8Array(decoded.length);
    for (let byteIndex = 0; byteIndex < decoded.length; byteIndex += 1) {
        bytes[byteIndex] = decoded.charCodeAt(byteIndex);
    }
    return bytes;
}

/** Creates isolated exact-output fixtures for the pinned TrueHD/MLP decoder. */
export function createTrueHDExactCapabilityFixtures(): readonly TrueHDExactCapabilityFixture[] {
    const fixtures: TrueHDExactCapabilityFixture[] = [];
    for (const fixture of ENCODED_TRUEHD_EXACT_CAPABILITY_FIXTURES) {
        fixtures.push(Object.freeze({
            accessUnits: Object.freeze(fixture.accessUnitsBase64.map(decodeBase64)),
            bitsPerSample: fixture.bitsPerSample,
            channelCount: fixture.channelCount,
            channelMask: fixture.channelMask,
            codec: fixture.codec,
            expectedOutputs: Object.freeze(fixture.expectedOutputs.map(output => Object.freeze({
                frameCount: output.frameCount,
                mediaTimeMicroseconds: output.mediaTimeMicroseconds as Microseconds,
                pcmFingerprint: output.pcmFingerprint
            }))),
            majorSyncRecoveryStartIndex: fixture.majorSyncRecoveryStartIndex,
            sampleRate: fixture.sampleRate,
            source: fixture.source,
            sourceSHA256: fixture.sourceSHA256
        }));
    }
    return Object.freeze(fixtures);
}
